why westwood shav her head
editor's not  lead wom connect you to extraordin wom of our time
each mon we meet two wom at the top of their field expl their car liv and ideas
cnn vivien westwood is as bald as a baby the faintest hint of downy whit hair sprouting across her nak scalp
painted pink eyebrow sweep dram outwards
wearing a sparkl wov brown dress resembl an expend hess sack she tot onto the stag at london's southbank art centre
straining forward in her chair the 72-year-old grandmoth of punk fash appear both vuln and fierce
fragil and yet fearless
the phenom vivien westwood
interview southbankc for wowldn ear today
pictwittercomau491ime6a the world was so mism and we hat the old gen becaus they wer doing anyth about it she say about forg britain's punk aesthet with then-boyfriend and sex pistol man malcolm mclaren in the 1970s
i dont hat the old peopl now i'm on of them
but i've been try to do someth to chang thing al my life
god sav the queen decad aft the coupl start their rad new cloth shop in an are of london cal world's end display rip t-shirts rub curtain and ev a liv rat in a cag westwood has becom on of britain's most prestigy fash designers
th is the wom who aft receiv an award from queen elizabe ii in 1992 fam twirl around for photograph without wear any underwear und her skirt
the provoc lady is stil ther though a littl mor frail-looking thes day speak at london's an wom of the world festival
buy less choos wel mak it last she tel a crowd of hundr most wom paty list to a lect that meand into clim chang bank and soc responsibility
campaign cult westwood appear almost reluct to talk about the superf fash industry she has conqu in a car span four decades
we fac mass extinct she says
it' being hid from us becaus our rul stil pursu their own vest interest they've been train to think that the peopl do not understand what's good for them
her trademark head of fiery red hair has been shav off not for styl but to draw at to clim change
westwood say she now plan to downs her hug success cloth empir in a bid to promot environ sustainability
i've got too much produc she says
i'm try to complet reduc the scal of operation
i'm cont on qual not quantity
what about thos peopl who cant afford her design clothes
it is difficult for people
but i think it's not good to just go to a supermarket and com back with bag and bag of cheap t-shirts
all thi consum is not a real choice
mad in britain born in derbyshir in nor west england dur world war two westwood's moth was a weav in a cotton mil whil her fath cam from a famy of shoemakers
a a teen in the 1950s she would alt her school uniform into fash pencil skirts
later she work as a teacher
but it was through meet sex pistol man malcolm mclaren in the 1960s who becam the fath of her son joseph ferdinand cor in 1966 that she real embrac punk rock
the couple's sou west london shop which at vary tim was nam let it rock sex and sedit - cloth for hero sold everyth from rub fet gear to pir outfits
the country was a morass of beig and cream bri-nylon and their shop was an oas said marco pirron of band adam and the ants
it took gre lib and bravery to wear rub in the street
if you shop ther you didnt go anywh else
noughties westwood cast yo ey across the most glam red carpet ev in the world today and youl lik to see a westwood design be it lily allen's princess dress at the bafta or pharrel william cowboy hat at the oscars
regardless of her hug success westwood stil talk of fight the establishment
i us my fash as a platform to talk polit she says
when you're a fash design you sort of design in a capsule
this is how you want peopl to be lik they ar at the mom but better
read meet the new gen of 'modelpreneurs read how angel ahrendt reinv burberry