why fun ar big deal in ghana
editor's not cnn's on the road sery bring you a gre insight into the hist custom and cult of ghana
cnn expl the plac the peopl and the pass un to thi afr nation
cn fun in ghan ar not on an occas to mourn
they ar also an opportun to celebr the lif of the dear departed
hardly ev a somb low-key affair ghana fun ar a soc ev attend by a larg numb of mourn which could reach hundr the mor the better
that mean the person was very friend very charit was good to soc was hav a good commun with the peopl within the socy say jamim a famy friend who attend the fun of the 70-year-old joann boafo in the town of kumasi
ghanaians may spend as much money on fun as on wed sometim ev more
an av fun should cost between 15000-20000 say kwaku a fun plan who is in charg of 30 fun party on thi on day alone
that includ the oblig giant col billboard that annount fun arrangements
the billboard which may cost from near 600 to 3000 ar plac at strategic spot for everybody to see oft dot the city skylines
most fun ar held on the weekend most frequ on saturdays
mourner us dress in black or black and red tradit fun cloth may travel to oth town or vil and in turn they expect the bereav famy to provid food drink mus and dance
th extrav also extend to the caskets
coffin hav becom a stat in ghana
they ar us bright col and elaborate
they may hav fancy shap that resembl the dead's favorit object or repres their profession
thus a carp may hav a coffin shap lik a ham or a sho for a shoemaker
there ar also casket shap lik coca-col bottl and airplanes
ghanaian rev the dead so much that fun ar at the heart of ghana soc life
lavish spend on fun has invit crit from polit and religy leaders
we ar invest in the dead rath than the liv  and that is bad legisl alb bagbin ont said
charles gabriel palmer-buckle the archbishop of accr said the surest way to rememb the dead is not the typ of coffin us to bury them nor is not the typ of clo or t-shirt won dur their fun but doing someth posit for the dead which would benefit the living
funeral rit also involv som off cry by mourn as wel as praying
the boafo lik many griev ghana famy hold a church serv for joann as well
but the rest of the fun rit is pur party time
i think she would be very happy say richard son of joann as mourn ar dant and hav a good time
i think if she is anywh if my moth is anywh right now she wil be very happy
see also ghan keep on of africa's star of democr shin see also bamboo bik turn around fortun for work wom in ghan yenn kwok contribut to thi report
cnn's on the road sery oft carry spons origin from the country we profile
however cnn retain ful edit control ov al of it reports
read the policy