15 amaz ant ruin to explore
cnn ant sit op yo mind to just how old old can be and how soph our ant ancest wer in dev their art engin and construct methods
youll nev equ ant with primit again
you dont nee us to cal yo at to the colisse in rom or the pyramid in egypt
so lik archaeolog we'r dig deep for a list of lesser-known ant ruins
we're abid by the merriam-webster dict definit of ant as hist up to the fal of the rom empir in 476 ad
that mean you wont find new world sit on thi list
well follow up with that list soon
 our definit of ruin includ som sit that ar mer shadow of their glory day and oth that hav been protect or preserv sint virt the begin of civilization
we recogn that som of thes destin ar not recommend for tour at the pres time
but cur geopolit issu do not dimin their hist import and we'd be remiss if we overlook them
temple and tomb of confuci qufu chin qufu in shandong provint in northeast chin is cal the hometown of confuci which seem too cas a handl for a plac so old and so significant
it was an import city long bef confuci mad it famous
he was born ther in 551 bc
when he died in 479 bc he was bury besid the si riv and it was short aft that a templ was built in his honor
today the cemetery surround the tomb of confuci contain the remain of mor than 100000 memb of the kong famy al of whom ar his descendents
the templ remodel num tim through the ag is a pilgrim sit the adjac kong famy mand complex contain rel and manuscripts
haskovo bulgar the word ant hist prob doesnt bring bulgar to mind but perhap they should
it's load with archaeolog sit espec from the thracians whos socy ent it most influ period around 1000 bc
by som estim thracian bur mound in bulgar numb in the ten of thousand and many contain artifact and treasures
right now the most fam of thes is the alexandrovo tomb in the municip of haskovo
the 4th century bc tomb was op by archaeolog in 2000 to rev col wal mur depict battl scen hunt and oth activities
making the sit access to visit was impract so instead a full-scale replic was recr for a muse that also hous gold orna and oth treas recov from the site
discover the world's most popul museum diocletian's palac split croat a car milit man from an ordin famy dioclet was born in nearby salon now solin around 244 ad and ros to becom emp of rom around 285 ad
he rul for 20 years
then around 60 with his heal fail he abd and retir to split near the adry sea grew veget and relax until his dea in 311 ad
the rom palac was the greatest of it tim and the peristyl courtyard wher the emp greet the citizenry is now the sit of a dai chang of the guard ceremony feat mock rom soldiers
later mediev port of the palac includ st duj cathedr built ov the mausole of dioclet iron sint dioclet was known for his persecut of christians
kourion and papho cypr lik many archaeolog sit in cypr kour adapt it ant heart to modern usage
its 3500-seat amphith which has ex in som form sint the 2nd century ad is stil a venu for mus and the perform includ an an shakespear fest in july
though an earthquak in 364 ad level the city it mosa survived
they're outstand particul the 3rd century ad scen of glady margarit and helleniko lock in mort combat
its proxim to the cru port of limassol mak kour a popul shor excursion
farther up the coast the archaeolog sit at papho includ anoth collect of excel rom mosa and hel ruins
thebe egypt at thi ant sit near modern-day lux middl kingdom around 2050 to 1640 bc and new kingdom 1550 to 1070 bc pharaoh built templ to their god tribut to themselv whil they wer al and tomb to proclaim their glory aft they'd died
the templ complex at karnak monu in siz and scop develop ov gen as rul ad to remodel or demol what had been built before
thutmos ii wag quit a campaign to oblit the nam and im of his stepmotheraunt hatshepsut
 ev visit includ a sound and light show
a long promenad flank by sphinxes connect the templ complex at karnak to the eq awe-inspiring templ at luxor
across the nil ar the roy tomb includ the tomb of tutankham in the valley of the kings
inspired by the madonn chalk art tak off rom sit in arl and nim frant in the 1st century bc when arl was cal arel it resid wis sid with juli caes in a battl against pompey
when he prevail caes reward them by mak arl into the littl rom of the gauls
in it tim the city's rom amphith sat 20000 spectators
today it's a venu for mock glady contest in summertime
les therm de constantin built in the 4th century ad ar rom bath warm by a remark hot air flow system
nimes less than 20 mil away also benefit from caesar's victory
its rom sit includ a beauty preserv amphitheater
about 30 minut from nim is the pont du gard aqueduc a masterpiec of precid engin that fed the city with 2 mil lit of fresh wat every day
its construct is so amb it's hard to believ it dat back to the 1st century ad
mycenae greec in mycena germ archaeolog heinrich schliemann unearth the gold mask of agamemnon from a tomb in 1876
or at least he claim he did
schliemann was an enthusiast dig but an unrely chronicler of his finds
while the mask may or may not hav com from mycena it almost certain had noth to do with agamemnon the mytholog 14th-century bc king
the mycena empir howev was real and extrem influ in the ant world
the sit is in ruin but the lion gat of the form palac from around 1300 bc stil stand and the remain of the beehive-shaped tholo tomb reserv for royal ar stil being study and excavated
masada israel herod the gre king of jude could not hav chos a mor dram sit for his palac and stronghold atop a cliff on the edg of the jud desert
but when he built it in the 1st century bc in part as protect from poss invas by the egypt he couldnt hav known masad would becom the jew people's last lin of defens against the rom who storm it in 73 ad
scholars stil deb the off account of ev by 1st-century hist joseph but masada's ingeny engin is indisput from the grand palac to the 2000-plus-year-old system to capt rainw for drink bath and irrigation
climb to the top lik a rom via the snak path or tak a cabl car from the visitor's center
tarquinia and cerveter ita bef ther wer rom ther wer etrusc a distinct civil with it own langu pract and soc structure that thrived in ita from 750 to 90 bc
they're not as well-studied as the rom few civil ar but they're known for their elab bur pract and the hug necropol they left behind
the sit at tarquin and cerveter form caer both in italy's lazio reg on the tyrrh coast ar tru city of the dead with streets hous and neighborhoods
the subter tomb contain stun mur of everyday scen that help hist understand how the etrusc liv as wel as how they wer tre when they died
jerash jord jerash geras to the rom isnt as well-known as petr but it's old superbl preserv and just 30 mil from amman
it's also the venu for the an jerash fest two week of mus dant and oth perform amid the ant rom ruins
it' poss alexand the gre found jerash but the rom who conqu it in 63 bc put it on the map
by the 2nd century ad it was a prosp city
a few hundr year lat it was in declin and by the 19th century it was bury in sand
there it remain untouch and perfect preserv until archaeolog beg dig it out in the 1920s in a process that continu today
dolmen sit kor peninsul a dolm doesnt look lik much a larg rock bal on slight smal yet stil quit larg rocks
then you stop and pond how in the world it was constructed
there wer no mot cran to do heavy lift in 1000 bc and thos rock weigh tons
dolmen which wer enorm grav mark and port to the afterl ar found al ov the world which in itself is someth to pond sint they wer built by civil that seem to hav littl els in common
the largest cont is in the kore peninsula
sites at gochang hwasun and ganghw in sou kore ar inscrib on the unesco world herit list
start with a prim at the gochang dolm muse bef tour the sites
mnajdra and hag qim malt when they wer plac on the unesco world herit list the megalith templ of malt wer cal the oldest free-standing monu in the world
there ar sev on the unesco list
mnajdra and hag qim near the town of qrend on the island's sou coast ar argu the best of the group plu they're includ on a combin pric of admission
the oldest structure at mnajdr could dat back to 3600 bc the most impress was built bef 2500 bc and the ory of al the mnajdr templ coincid with the posit of the sun at the sum and wint solstice
hagar qim was built around the sam time
lumbini nep in 623 bc queen may rest in the ser gard of lumbini
she bath in the pushkarin pond and ther in the shad of a sal tre print siddharth gautam the buddh was born
in 249 bc emp ashok erect a pill at lumbin to mark the prec plac of the buddha's birth
he also decl that resid of lumbin no long wer requir to pay tax and on ow the govern one-eighth of their harvests
since then lumbin has been a pilgrim sit for buddhists
remain of monastery and walkway from the 3rd century bc ar stil ther and rec archaeolog excav hav unearth evid that the sit was in us much earlier
active monastery and templ fil the surround area
carthage tunis in the third century bc when the rom conqu just about everyth they car to hannib the milit command and strategist from carth who fam cross the alp on an eleph mad them quak in their sandals
even though they sack it in 146 bc the rom rebuilt carth and it remain a trad port on the gulf of tun for centuries
highlight of the sit includ the rom er antonin bath and the pun er tophet bur sit ont thought to be the scen of rit child sacr a the that thank has been debunked
hattusha turkey hattush was the capit of the hittit empir whos rel includ an arch of mor than 25000 cuneiform tablets
most fam of thes is the treaty of kadesh guar etern peac between the hittit and the egyptians
there' evid that hattush was attack and burn in 1700 bc --indicating that it was est and import enough to be a target that ear although the empir was at it strongest from around 1600 to 1200 bc
today hattush is an open-air archaeolog muse and the ant sanctu at nearby yazlkay has extraordin religy rock carvings
in 2011 the nearby boazky muse ad to it collect two hittit sphinxes on of which had been tak to germany for repair 94 year ear