harry potter's new park
cnn a fire-breathing dragon self-stirring cauldron and dant skeletons
these ar the thing muggl dream ar mad of
but they wont be dream much longer
this sum univers orlando wil op the door or rath the secret ent to the wizard world of harry pot diagon alley at univers studio florida
once insid the elab them are which has been in the work sint the sum of 2010 guest wil feel lik they've step onto the london film set complet with the popul wizard pub the leaky cauldron sev icon shop and a marqu rol coaster-type attract bas on gringot the goblin-run bank from the series
the wizard world of harry pot hogsmead which op in jun 2010 at universal's island of adv was on of the most talk about new attract of the past decad within the industry and has been wild popul ev since
by august 2010 harry pot and the forbid journey the star attract at hogsmead hit a mil riders
parent company nbc univers report a them park revenu increas of mor than 30 in 2010 thank in larg part to the wizard world's op that year
in 2011 them park revenu jump again by near 25 follow by a modest gain in 2012 of about 5
park op from around the world wer impress by the immers expery univers cre and the metic at to detail they us to bring the harry pot story to lif say david mandt vic presid of commun for the intern assocy of amus park and attractions
there is gre anticip within the industry to see how diagon alley wil build on that success
cnn got a tour of the 20-acre construct sit which rough doubl the siz of the harry pot expery wher thousand of design engin and craftspeopl ar hard at work prep for op day
here ar som thing to know it's hid the outsid of thi attract is a hodgepodg of build facad built to scal includ the wyndham the leicest square's tub stat and grimmauld plac which mask the ent to diagon alley
here guest wil be abl to meand along the london waterfront sit und the shad of tre and gaz at a replic of london's ero fountain
guests wil ent und the arch of the leicest squ facade
however univers has not said how exactly
in the sery harry ent diagon through a mag wal of bricks
once insid guest wil be immedy immers in a bustl wizard hub within a muggl city wher tow build ar slight askew with steep staircas and jag edg galore
ther wil be goblin the star of it al is gringot which in the sery is a mass goblin-run bank that harry visit to get money for his school supplies
in the real-life vert visit wil be in aw of the marbl lobby and cavern passageways
theyll tak off from her on a multi-sensory thrill rid through the vaults
and the dragon that wil perch atop the bank build reminisc of when it escap from the bank in the sery real doe blow a giant bal of fir quit frequ say mark woodbury presid of univers creative
your ticket to univers studio giv you access to diagon alley admit into univers studio florid 92 for adult and 86 for kid ag 3 to 9 allow you to roam around the park and visit diagon alley
however if you'd lik to pop ov to hogsmead via the hogwart express you must purchas park-to-park admit 128 for adult 122 for kid ag 3 to 9
the train wher harry meet pal herm and ron in the first movy wil shuttl peopl ov to hogsmead in island of adventure
along the way rath than see backst area between the park guest wil see view of london and the brit countrysid thank to som high-tech features
it goe beyond the booksfilm jk rowl provid univers with nam that didnt ex in the book
for inst in diagon alley visit wil find horizont alley and carkit next to weasley wizard wheez and the train trellis
although the world-famous auth has not tour the sit yet she has been involv as us in the develop process and has been a gre support throughout the process as she was in the origin in 2010 say woodbury
just a delight to work with and a wond author
and someon we ar etern grat to for cre a body of fict that is so rich that giv us an opportun to develop what we'v been abl to do
there wil be new merchand and food al the bit and bob that any good wizard nee wil of cours be available
shops wil includ madam malkin's rob for al occas for hogwart scarv and charact costum the three-story weasley wizard wheez shop for mag jok and toy the mag menagery for owl and hippogriff stuff anim qual quidditch supply for broom and quaffl and more
wand shop ollivand wil be ther too
note the ollivand loc found within diagon alley is the origin loc as ref in the harry pot book and films
th shop wil be larg than the cur on found within hogsmead at island of adventure
 the leaky cauldron a popul wizard pub and in from the sery wil be a coloss spac serv butterb and tradit engl pub fare
nearby flor fortescue's ice-cream parlo wil serv weird flav lik strawberry with peanut butter
it wil blow hogsmead away we think the expery is expon say woodbury
it's not just on and on is two
in thi cas it's on and on is six
actor matthew lew who play nevil longbottom in the film cont it's ridic lew said aft tour the sit yesterday
the scal of it it's just enorm