the light of diwali
cnn firework boom bulb flash and flam flick as ten of mil of peopl across the glob celebr the begin of the fest of lights
diwali from the word deepaval mean row of light is observ by hindu sikh and jain commun who celebr for fiv day in autumn to mark the vict of light ov darkness
th year the fest begin on novemb 3 with splashes of col light display and blar party set to greet diwali's arrival
celebrated for century across much of the ind subcontin diwal is now explod spreading the prom of weal knowledg and happy to new commun across the world
from ind for the diwal newcom photograph roy del vecchio expert capt the outsider's inaug into the fest snap the delight fac of a man who had invit him to join the celebr on his roof
39-year-old del vecchio say he had travel to rajasth to see the fest when the man hold the sparkl had invit to join him and his son to light firework and shar tradit sweets
more cnn celebr halloween som of you ar pretty twist firework ar said to driv away evil spirit and at thi tim of year many hind wil also cle the hous and light smal oil-burning lantern to attract lakshm the goddess of weal into the home
but the celebr is anticip with excit by many across ind as wel as neighb sri lank and nep regardless of religy beliefs
i do celebr diwal mor for the spirit of the fest rath than it religy imply say ireport samarjit mazumd from bang india
to the world mazumd capt on of diwali's tradit symbol a swastik assembl from marigold flow which symbol peac the 32-year-old explains
but thi year's celebr ar lik to be anyth but peac with an explod of diwal party light up city across the world
read 10 thing ind doe bet than anywh els rec year hav seen diwal party pop up in loc from ontario canad to melbourn austral wher tradit diwal celebr mix with showcas for ind food mus dant and film
from singapore's littl ind district to rur somerset uk ireport hav sent pict of diwal light shin out
meanwhile in guyan a hug motorcad rol through the capit georgetown as capt by guyan nat amand richards
the country's 200000-strong hindu pop lin the rout and oft wait for hour to see the parad pass by
richards say she's already plan wher shel go to wait for thi year's motorcad and join the mil of oth across the world hop to catch a glimps of the light