13 gramm and spel fails
cnn going to a resta is suppos to be a relax experience
but for katherin dil ther was on thing that was guarantee to stress her out see caes salad misspel on the menu
it would just driv me bal dil said
after year of pract she's learn to relax
now i just shrug it off
i stil not it but it doesnt driv me crazy lik it us to
many of us hav a tend to not bad gramm and misspel as evid in the gallery above
but for cop edit the peopl who read and edit story for gramm styl and subst fix er is their job
in hon of nat gramm day on tuesday we sat down with dil on of the funniest gramm gatekeep on the cop desk
she has been a cop edit for 15 year six of which she's spent at cnncom in atlanta
the interview has been edit for clar and brevity
cnn what mad you want to becom a cop editor
dilling i want to be a writ first act but i took a report class in colleg and hat it
i didnt lik going up to peopl say yo hous just burn down
how did it feel
at the sam tim i was tak an edit class
it cam easy i enjoy it and it seem lik fun
cn what ar the most common er you com across in yo job
dillinger wher to start
it's prob punctu er spec comm er with independ and depend clauses
spell check mean most peopl us dont mak spel er unless they just dont pay any at at all
most peopl get verb tens correct
and capit  peopl lov to capit thing they shouldnt
cnn what ar yo biggest gramm pet peeves
dillinger misus of the em dash when you should hav a colon instead driv me crazy
and i real hat the word prob just in general
i hav a bunch but thos ar my two main ones
i'm const tak em dash out of stories
learn the colon
there ar prop way to us a colon
i shak my fist at you
cnn could you ev be clos friend with someon who mak lot of gram mistakes
dillinger i us to dat somebody who did back in college
h was as bad a writ as you could get
i us to typ his pap for him and edit as i was going
you learn to liv past it i guess
cnn hav you ev mad a mistake
what's yo most mem one
dillinger oh god i've mad so many
that's the nat of the business
when i was in austin on the cop desk of the loc newspap ther was a mon wher i just mad on aft another
it was terrible
it's yo job not to do thos things
i've put incorrect inform into stories
it kil you every tim you do it too
luckily non of them has been libel or got me cal up to the publisher
cnn what's the best gramm fail you've seen
extra point if it mad you laugh
dillinger wher they misspel the team nam on a jersey
those alway crack me up
it's not a gramm fail it's mor of a spel fail
cnn the gramm rul that must nev be brok is  dil you can mak an argu that within reason you can break almost any gramm rule
you learn ov the year that it's ok to break the rules
it' al in how you wer taught
you go by what thi story say to you
if thi story splits an infinit but it work then i would split the infinitive
how the story sound is sometim mor import than being tot adh to every gramm rule
cnn how wil you be celebr nat gramm day
dillinger every day is gramm day when you're a cop editor
is gramm real import to you
what's yo biggest gramm pet peeve
all gramm ar welcom to discuss thi in the com below