sperm bank shock we'r sisters
cnn look at them you can see the simil the nos the cheekbon the dimpl chin and long brown curls
but what ar the chant right
wh ar the chant that two californ teen would meet onlin in a room hunt cross the country to attend louisiana's tul univers and learn a semest lat they wer half-sisters the daught of the sam colomb sperm donor
emily napp 18 of san francisco and mikayl stern-ellis 19 of san diego learn exact that janu 7 when act on a susp they'd jok about sint father's day the wom ask their moth to hunt down their sperm don numb from the los angeles-based calforn cryobank
stern-ellis was in a doctor's office
sh had ask her moth to send her the number
nappi had don the same
they both text me at the sam tim and it was the sam numb stern-ellis said
i was just star at my phone
i didnt know what to do
i think the on way to describ it is mind-blowing
now that they know they're sist it al mak sense
they hav the sam build and ar abl to shar cloth but sad not sho and they're sci maj with stern-ellis focus on anim napp on psychology
they both sleep-talk and sleepwalk report the advoc in baton roug and dur a black friday shop trip ov thanksg break they independ purchas the sam sweater
it was their common that drew them to each oth in april
while prep for colleg they took a room survey and found they both had lesb par and a pass for the the advoc reported
we had so much in common that i decid to e-mail her facebook mess her and see if we could be room stern-ellis told cnn
that didnt pan out but the two stay in touch and in jun stern-ellis post a tongue-in-cheek facebook mess on father's day thank her colomb sperm don fath for the x chromosome
whoa napp thought
her moth too had us a colomb sperm donor
she reply to stern-ellis to let her know say she didnt want to be creepy
the two had fun with it and went al first semest going that girl might be my sist  napp said
we just thought it was a joke
over wint break their curios got the bet of them
they had to know so they reach out to their moth and ask them to find the sperm don numb and they learn in the first week of the new year that they had a new sibl just sev month sep them
there's someth so famili in her fac when i look at her napp said
ad stern-ellis everyth you dont see in our mom you see in us
according to the advoc nappi's moth said she select the 19-year-old sperm don becaus he was handsom tal athlet and interest in ecology
stern-ellis mom had simil reason and was drawn to his colomb herit and dark skin the newspap reported
the sist ar now play catch-up
they're learn the bas about each oth stern-ellis favorit col is purpl nappi's is gray and we'r real clos but there's littl thing that ar real ess about our being that we dont know about each oth stern-ellis said
as for hunt down thi strapping intellig colomb gent who fath them it's on are wher they differ
nappi say she'd be cury to see what he look lik but she doesnt hav any real urg to meet him
i dont feel lack in any way she said
but her sist has long to find him sint she was a littl girl though find a sist instead wil sat her for now
since thi hap i'm definit going to wait a whil becaus emy is mor than enough
watch new day weekday at 6am-9am et
for the latest on new day click her