dian von furstenberg's icon wrap dress turn 40
editor's not michael angel dav a writ and act was the execut fash beauty and cult edit at ess editor-in-chief of honey magazin and fash direct for vib magazine
cnn america's most bril docu decl al men ar cre eq howev the sam cannot be said for al dresses
forty year ago dian von furstenberg cre a supery yet remark democr dress
though von furstenberg was on in her 20s an awkward tim for many young wom she prov to hav perfect tim when she unleash her littl dress onto the am fash landscape
and littl did she know that it and she would becom the timeless icon of glam pract they ar today
the 1970s wer a tim when many wom wer ent the white-collar work forc and also decl their sex independence
this was a rad combin of recogn newfound profess pow and redefin old sex restrictions
diane von furstenberg gav thi new wom someth new to wear for her new car and new sex life
th wrap lit dress the movement
it lib wom from the stuffy and stiff male-imagined work gal get-ups it was easy to put on and tak off it was smart afford and travel well
the fabr was clingy but not cumbersom it celebr a woman's silhouet instead of try to control it
the wrap dress would sway with a wom to her first big job then seamless swing with her to her first hot date
dvf design a dress for the new am wom on the move
rarely hav we seen such a democr design
the dvf wrap dress embrac divers lik no oth bef it or since
it can be worn wel by wom ag 20 to 70 and siz 0 to 20
it com in class solid and a plethor of print can be lay with everyth from denim jacket to floor-length furs
pile of jewel can fil the op front v-neckline or an eleg collarbon can be the sol accessory
the dvf wrap dress is oft the symbol that on has got her first real job yet it is eq appropry if you occupy the corn office
as many wom abandon ear adult outfit the wrap dress endures
most cloth design ar intend to dat you socioeconom plac you loc and lock you in som posit or lack thereof
but not thi pow piec it has the flex to grow with you as you becom the ful self-determined self-defined wom you want to be
a wom get to fil the wrap with her poss and that's it genius
the dvf wrap is the am dream dress
using herself as mus dian von furstenberg had a vis for who the am wom would become
sh has been known to say she wasnt sur what she want to do but she knew the wom she want to become
and ev bef she becam the dvf we know and rev she gav that wom and mil of oth someth wond to wear
the class swe ballerina wear in rehears pair with a fluid skirt von furstenberg rev inspir the wrap dress
perhap she foresaw herself and oth am wom mak grac glob moves
aside from being a sharp businesswom whos good can be purchas in mor than 55 country in 2006 she becam presid of the council of fash design of americ the industry's most influ organization
in 2012 forb magazin nam her on of the 20 most pow wom in business
she has put herself in the cent of sev humanit and philanthrop effort includ bornfr a campaign to erad the spread of hiv from moth to child by 2015
yet at the cor of her busy at 67 she say she's nev work so hard multiplatform lif is her foc on women
in a rec new york tim interview von furstenberg stat everyth i do now is for the empow of women
and it is certain she has sec her legacy
like the decl of independ a dian von furstenberg dress has been hous in a prestigy institut in washington the smithsonian
in 2009 first lady michel obam wor a chainlink-print wrap dress on the obama first off whit hous christmas card
the sam year form vog contribut edit andr leon talley cur the retrospect dian von furstenberg journey of a dress which op in moscow
in 2010 the show went to so paulo brazil and in 2011 to the pac gallery in beijing
it has sint been re-imagined and expand for it am debut at the hist wilshir may build in los angeles
the show of dress photo and origin art op to the publ on janu 11 and wil run through april 1 2014
the 40th birthday party of the dress that mad the car that mad the icon wil go on year-round with limited-edition collab with the andy warhol found and a book the wom i want to be com in the fall
with americ fac the very real poss of a wom win the whit hous in 2016 dian von furstenberg's 40-year-old busy model of invest in independ wom celebr freedom and sel confid appear to be mor tim than ev