stud say bye to snow days
cnn ear thi mon zak terzin rous himself about fiv minut bef his engl class beg and didnt panic
instead the high school sophom grab his ipod and check on a class discuss of the autobiograph of malcolm x without ev get out of bed
a snowstorm anoth on had cancel class in the pascack valley reg high school district in northern new jersey but educ and stud wouldnt be tak a day off
before the snow fel ev bef the off school cancel cal teach wer prep par wer warn and stud had receiv enough assign to fil a snow day
school lead around the country ar tear up their calend to cram in mor teach tim aft extrem numb of weath cancellations
some ar elimin holiday break and profess develop plan ad minut and day to the school clock or ev cut recess and op school on saturdays
but a few ar try someth diff virt school day that continu learn ev whil staff and stud ar stuck at home
this could be the snow day of the not-too-d future
as much as stud lov them school off loath calam cancel thos day off caus by snowstorm hur il outbreak or pow outages
they cost tim and money disrupt the flow of learn and leav par in a lurch
by mid-february the 2000-student pascack valley reg district had already us it three built-in snow day for the school year and superintend p erik gunders didnt want to chip away at spring break
with snow in the forecast gunders alert teach that he expect to cancel class and ask them to develop lesson stud could complet from home
a day lat when stud log in on school-provided laptop they wer abl to ask teach quest work through assign or jump into class discuss ev if they sometim took break to shovel the walkways
pascack valley reg off stil dont know if the day wil count toward their state-mandated total
the new jersey depart of educ hasnt decid yet
but the superintend already count it as a learn success
we think it's worthwhil and produc why not do it
gundersen said
this is what we'v been doing in the corp world for quit som tim  bal famy lif with work and get thing done
why shouldnt high school kids
we're lucky right
schools in simil circumst ar com to the sam conclusion
staff and stud at coyl and cassidy high school in taunton massachuset tri their first virt school day aft cancel beg to pil up thi year
they wer ready
all of the priv school's 500 stud now hav an ipad purchas by his or her par and they've us the tablet in class and at hom sint the start of the school year
they wer lucky too to hav the perfect snow day said kathleen st laur vic princip of academ affair at coyl and cassidy no widespread pow out no long stretches of day off a forecast that gav teach tim to prep and a stud body that already knew the drill
teachers found cre way to record and shar lesson and many spent the virt day field stud quest st laur said
parents lov it and stud wel they wer a littl bum out
many slept in and som complain ther was too much work ther wil be mor coordin among teach in the fut st laur said
still particip was high
wi kid a day out is a lot st laur said
this way everyon could hav the sam lesson just as if they wer in the classroom
read 5 reason schools wont cancel for bad weath going into pascack valley regional's virt school day teach fear som stud wouldnt log in despit warn that the day's assign would count toward their grades
it wasnt a problem the virt school day had high attend than they expect on a norm school day the superintend said
it was energ invig said soc study teach kar kosch who has taught in pascack valley schools for 28 years
i dont mean to sound corny but we wer al in it together
no sery techn glitch wer reported
next tim kosch said shel hav a stronger sens about how to pac convers held among doz of kitch tabl and couches
a on stud put it kosch said  i dont know what the big fuss is
we do thi every day
kosch of cours rememb the year bef everyon had a laptop but she had to agr we'r lucky right
this is a vac day in area wher weath cancel ar common stud hav long been expect to haul hom backpack ful of book and assign bef snow day and som schools hav tri to light the load through technology
in ohio schools can us blizzard bag onlin or hard cop of assign to keep stud learn and day counting
even at schools that provid an onlin bank of act it can be comply to keep an entir class mov forward said dick flan deputy execut direct for program and serv for the nat assocy of second school principals
technology off som prom in term of mitig som impact flan said
depending on a particul child what kind of learn a child may be how dilig wil they be to eng on a snow day in som sort of academ pursuit when thi is a vac day
tougher yet is the technology
most schools dont hav one-to-on program that supply stud and staff with comput and hom internet connect can stil be spotty
teachers pol for a 2013 survey by pew research center's internet  am lif project said mor than half of stud had sufficy access to digit tool at school but on a fif could access digit tool at home
read the real class behind the sup bowl commerc ev without schoolwide technolog program individ teach ar find way to keep their stud on track
the day bef a febru snowstorm swept through the atlant are teach jord kohanim sent her stud hom with the sam instruct she rep al year check the class website
most of her stud at northview high school outsid atlant hav mad it a habit and with the help of tool such as remind101 a serv that allow teach to send text mess to stud she was confid they would follow through
when an ear stretch of bad weath caught schools by surpr sev stud check the websit and complet assign without her ask she said
it's not the highest qual educ out ther kohanim said there's littl chant for interact when stud ar ask to read a pass watch a video and writ a response
but kohanim mad herself avail to answ quest and check work and it help to keep stud focus until they return the follow week
i wouldnt say i'd lik that to go on for long said kohanim who has maintain a class websit sint she start teach sev year ago
we dont hav tim to stop on snow days
we hav to keep moving
a nerd's dream on the morn of febru 13 pascack valley high school engl teach mat moron was mayb a quart of the way through his morn coff when stud beg to respond to the autobiograph of malcolm x on twitter
some teach us googl docu or learn tool such as my big camp schoology or canva for the virt school day but he espec lik see the convers draw peopl who wer ev in his class
th was a nerd's dream for me said moron himself a gradu of pascack valley reg schools
for stud it was a lesson in tim man and self-driven learn on he's sur theyl tak to college
for teach it was a chant to try idea they've on pond before
for everyon else
proof
w ar in a fortun posit her  but you dont nee a whol lot of infrastruct to do som of the stuff we'r doing moron said
there ar mean by which to do this
a lot of twit discuss is through ipad cel phon whichev glow rectangl you want to us that's fine
read wil googl glass go to yo class
student wer learn oth lesson too
zak terzin discov he had to be cont becaus he on had 140 charact to mak his point about malcolm x
he list mor too
he's a talk he said an athlet the class presid a guy who's alway ready to jump in with an opinion
online he fin heard som quiet classm speak up
having it al out on twit peopl hav that littl barry he said
it was kind of op to a lot mor opinions
between shovel snow watch an olymp hockey gam and mak himself a sandwich he list to a teach explain som algebr conceiv complet som hist work and forc himself to fig out som stoichiometry problem that he might've giv up on if he'd been in the sam room as the chem teacher
i thought we'r just going to get extr homework
it was kind of ridic to hav a virt day he said
but the mood definit chang aft it went successfully
they got us involved
they wer assign the right amount of work
i got don at 251 and i cant believ i act got done
would you want virt school day to replac tradit snow day in yo area
tell us why or why not in the com on twit cnnschools or on cnn living's facebook pag