would you wear pjs in publ 
cnn admit it you've gon to the grocery stor in yo pjs
maybe you just nee half and half for yo morn coff or went out aft a day of marathon whol season of divin design
maybe you real lik how yo pajama feel and aspir to wear them hugh hefner-style which is to say as oft as possible
but deep insid yo soul in the plac that determin the diff between right and wrong clinton kel believ you know it's taboo
it's a univers fash affront tied into soc appropry the what not to wear styl mav said of loos knit ensembles
he' wit noth less than a paradigm shift in am conceiv of appropry cloth ov the past 10 year on what not to wear as he help 600 fash victim learn to put their best fac and well-dressed-self forward
but the al of pajama yog pant and track suit is strong
we ar continu as a cult on thi downward spir of styl kel said i think that ther wil alway be a group of peopl a strong perc of the pop who wil car about their appearance
but now we hav permit not to care
what changed
he said it's that peopl no long fac the sam soc press they would hav century ago or ev a coupl decad ago
that soc press the unwrit rul about how someon should or should not dress has alway ex said sus kais a univers of californ dav profess in textil and cloth and wom and gend studies
clothing has been describ as a broadcast sign the way it commun kais said
we know an appropry outfit when we see it
when someth doesnt look quit right then we not that
th knowledg is cal a soc norm she said and the norm surround fash incorp the funct of cloth as wel as the cult attitud of the day
we're a pretty purit kind of country kais said
that has influ our cloth a lot
as a result am soc norm hav alway boil down to modesty she said
colonists hard show any skin or ev hair in publ an aspect of am dress that didnt chang much until the 1900s
the not of priv has been intertwin with idea of modesty sint colon day as wel said kar herbaugh the cur of the am textil hist muse in lowel massachusetts
while perform chor around the hous or going to the market colon definit would not hav been wear cloth that would hav been consid priv herbaugh said
they would hav been wear al the prop lay of clothing
in colon tim that meant wom would wear a chem a corset a corset cov a bod multipl lay of pettico and then a dress herbaugh explained
and you would hav been wear that regardless of wheth you saw someon els or not she said
it just wouldnt hav been appropry otherwise
th lin between publ and priv cloth start to blur with the adv of the indo wrap dur vict tim herbaugh said
these wer consid appropry for a wom to wear to receiv a wom friend at her house
they stil wer prop they wer just a littl less restrict she said
barely mor form than a rob thi precurs to the houseco allow wom the opportun to be in a semipubl situ without hav to wear al the bustl and pettico that publ dress us required
men had their own vert of wrap as wel she said
still it's a far cry from the pajama-clad par herbaugh see drop childr off at school
that bound of publ and priv dress has mov from the hous into the neighb kel said
we no long seek clu about appropry dress from our community
these day we look to celebr he said
i think that on photograph of on celebr wear someth inappropry can valid someon he said
and they wil leav the hous wear the sam thing
before cameron diaz was photograph wear ug boot no on would hav consid wear them in publ he said
the cult of comfort is not on determin by styl starlet said kais the textil professor
clothing expery a revolv in the 1960s thank to textil such as polyest rayon and spandex as wel as mass produc technology
rudi gernreich the fam design in the 60s known for design the one-piec topless bath suit was also known for doing a lot of knit she said
he predict that we would al be wear lik knit dancewear by now
and i think he's kind of right
we've becom accustom to a kind of comfort level in knits
but the devil is in that forg detail of stretch kel said
it's very easy in thi country to do two thing he said
one overeat
two wear real comfort clothes
the problem is when you combin both of thos thing you get caught in a spiral
large port of cheap ov process food keep us wear stretchy knit cloth that mak it easy to eat mor larg overprocess portions
i've heard thi from wom tim aft tim bef you know it you've gain 30 pounds
and then you get to a point wher it's hopeless i cant los 30 pounds
what' next
you say uh i giv up he said
ill keep wear my big comfy pants
would you wear pajama or oth ultracas cloth outsid the house
tell us why or why not in the com on twit cnnliving or on cnn living's facebook pag