most bizar hotel guest requests
cnn concierg request ar typ predict ticket to a show flow art chocolates
but som guest demand a tru outland hotel experience
th abl to fulfil thos peculi request sep the profess concierg from just the schmoes who work at the desk
life-size statu replica in chocol michael rome chief concierg of the the tow waldorf astor in new york has seen vary paranorm concierg request dur his ten of 20-plus years
he most vivid rememb the aust coupl crazy about candy
they want near life-siz statu of themselv for their wed mad out of chocolate
th pastry chef at the waldorf had on their photograph to work with rome says
it took sev month and sev email back and for to get the statu dimend just right
more insid the world's most expend hotel room camel at the loew ventan canyon resort in tucson arizon lead concierg victor cot was on the first mon of her job when a guest ask wher he could purchas two camels
refusing to get her rooky feath ruffl she loc a deal 35 minut from the hotel
the guest went to view the camel but decid against purchas them cit a miss hump
more 11 wildl expery that could van in yo lifetim kob beef for the dog at the st ermin's hotel in westminst london a guest request a dai supply of kob beef fillet for his dog
the concierg team bought and coury the steak from a nearby resta daily
two 150-gram kob beef steak retail for rough 50 in england
more 12 of the world's dog-friendliest hotel unicorn at the hotel indigo in ashevil nor carolin a guest ask for a unicorn to be wait in his room upon arrival
concierge katy brown purchas a unicorn plush toy and draft a cheeky but amy not as a spec surpr belov guest we saw yo request for a unicorn
unfortunately thi is the wrong season
due to their migr habit unicorn cur inhabit the second star to the right of twilight
they ar expect to return to ashevil sometim thi june
in the meantim as ashevil is known among many circ as the unicorn capit of the sou we hop that you can acceiv thi very acc art rendit of our nat fauna
if thi is unacceiv we do profus apologize
as you ar not the first guest to express interest in our loc wildl we hav plan a meet with the head unicorn lord mang biffy of the rainbow on perhap adjust his peopleshorsesmyth cre mov to somewh outsid the univers to bet align with our guest wishes
our sincerest apolog the socy of prop and right unicorn caretaking
more top fix for the super-rich travel hangov party when a fortun 500 company contact vega luxury group vip to help them throw a hangover-inspired party the concierg serv got them a gre rat on the sam suit us in the movie
added to the mix wer savvy bartend a dj and vary rel charact a 250-pound guy in a baby suit two peopl in tig costum a mik tyson lookalik peopl in toga and oth dress as charact from the wolf pack
more the morn aft asia's top hangov cur scat dog ash in the sea an eld wom contact the hilton haway vil in honolulu to ask if she could scat her dog's ash in the sea
concierge bert momotom spok to the lady and discov her belov pooch aloh pumehah who had been born in honolulu had rec pass away
local cano and chart boat club prov too pricey
then atl submarin agree to tak the lady out to sea dur their last shuttl to the sub and at no cost
momotomi escort the wom and help her scat the dog's ash in the ocean
i had obtain a lei from our lei-making instruct and we pray togeth as we toss the lei into the oc momotom says
it was extrem grat to help thi wom who had tear rol down her fac with her dream of bring aloh pumehan home
mor insid guid best of honolulu mariach band propos on gold gat bridg at the kenwood in and spa in sonom californ a gentlem want to part recr his first dat with his girlfriend list to a mariach band at a mex resta so he could pop the quest on bend kne in the middl of the gold gat bridge
with sec at an all-time high it was short aft 911 chief concierg er edenfield had to sneak sev guy onto the bridg walk in opposit direct hav them put on their sombrero in the middl of the bridg pul out their instru and play a tun whil the man kneeled
it caus quit a stir on the bridg that day say edenfield
she did say ye thank but it was on of the hardest request i've ev been ask to fulfill
more 25 of mankind's greatest engin achiev custom fingerprint art at the four season resort the biltm in sant barbar californ seny concierg katy al was fac with an ir guest whos wed centerpiec a custom fingerprint artwork hadnt ar in the mail
the wed was hour away
in a few hour the concierg found an art and had a coury pick up the appropry canva and paint say allan
the art cre artwork simil to the origin the team had to blow dry the canva to ens the paint dri in time
mor wher to get marry world's best wed venu ev mad yo own unus request to a hotel concierge
tell us about them below
charu sur is a travel writ bas in new york cov luxury destin cult veget food and the digit commun