22 spot for spectacul starry skies
cnn as the new sery of cosmo on avail to fox view in the unit stat seek to unveil the wond of the univers you might be inspir to seek out thes astronom spectac for yourself
thankfully there's a ready-made list of plac that off the best chant to spot met see star and pond constellations
the intern dark sky assocy id rec ad two plac to it cert list a dark sky reserv in germany and a dark sky park in the unit stat tak the numb of off recogn star-gazing spot around the world to 22
the id is a non-profit org fight against light pollut to preserv the qual of the night sky
misdirected and excess light ar the main caus of sky glow and light pollut say chip harrison park man for cherry springs stat park in pennsylvan on of the ida's cert dark sky parks
the id grant dark sky park and dark sky reserv stat to loc ded to preserv high qual night sky darkness
surprisingly the darkest night ski ar al in remot areas
one of the ida's aim is for reserv and park to be accessible
dark sky park and dark sky reserv ar som of the best plac on ear to expery tru dark night ski becaus they ar both dark and mor import access say dr john barentin dark sky plac program man at ida
many ar already well-visited nat and loc park which mean that by design them we hav the best chant of bring as many peopl as poss into contact with the altern awesom and endang resourc of dark night skies
international dark sky reserv westhavelland intern dark sky reserv germany design febru 2014 westhavelland nat park is the closest intern dark sky reserv to a maj pop city
known in germany as sternenpark westhavelland star park westhavelland the nat park is approxim 100 kilomet west of berlin
you can see the milky way and rar display of the auror bor say dr andrea haenel direct of the muse am schlerberg's planetar and who led effort for ida's designation
i think the most fascin expery is in autumn when thousand of migr bird wild gees and cran giv an impress background sound und the starry sky she says
the darkest and clearest ski ar between mid-may and mid-july dur the new moon from midnight to dawn
under thes condit zodiac light sunlight scat by dust in spac and gegenschein a faint bright of zodiac light at midnight can be seen
westhavelland nat park stremmestrae 10 14715 milow land ot milow 49 033 86 211 227 kerry intern dark sky reserv ireland design janu 2014 the reserv is a brand new baby on the ir tour menu say july ormond chairperson of kerry dark sky group and project man of the kerry dark sky reserve
th reserv span an are of 700 squ kilomet on the iveragh peninsula
its loc between the kerry mountain and atl oc provid nat protect against light pollut from oth ir cities
most of the 15 mil tour that pass through thi reg stop to photograph the landscap in the day she say few visit at night despit the starry show of milky way star clust nebula and meteors
on a clear night you can see the milky way's closest neighb 25 mil light year away the andromed galaxy
kerry is hom to few than 4000 resid and it top stargaz spot ar easy access by car
st finian's bay is at the cor of the reserv off on of the best night sky view without any ting of light pollution
kerry intern dark sky reserv  353 0 87 7845688 pic du mid intern dark sky reserv frant design decemb 2013 around 110000 stargaz each year visit the reserv to view zodiac light the milky way and constel say nichola bourgeo project man of the intern dark sky reserv at pic du midi
pic du mid cov 3112 squ kilomet spread across the pyrn nat park and pyrnes-mont perdu a unesco world herit site
th most popul spot for astronom view is at the observatoir midi-pyrnes built in the 1870s
the observ hous on of the world's highest museum at an altitud of 2877 met with exhibit on astronom and the hist of pic du midi
each year around 3300 night sky watch stay overnight at the observ for the night at the summit package
th highlight of the stay is a tour of the two-meter bernard lyot telescop the largest in france
you can also combin the trip to pic du mid with extrem sports
astrophilic extrem ski can mak their own way down the vertigin slop for no extr charge
pic du mid intern dark sky reserv rue pier lamy de la chapel 33 08 25 00 28 77 round trip cabl car and visit of summit and muse from 36 49 per adult 23 31 per child 5-12 year fre for child up to 5 year mor best hotel for stargaz brecon beacon nat park uk design febru 2013 mar and jupit stand out bright against the dark sky at brecon beacon mak them easy to spot without equipment
using a telescop you might see the galil satellit io europ ganym and callisto
the group of jupiter's four largest moon was nam in hon of galileo galile who observ them mor than 400 year ago
sugar loaf mountain has the darkest ski on the reserve
several smal road off the main a40 road lead up to the hil mor than 335 met abov sea level
the vant point off wid view ov the usk valley from abergavenny to crickhowell
if you want to mix hist welsh architect with stargaz you can enjoy the silhouet of the llanthony pri against the night sky
parts of the ruin wer convert into a hotel and pub
after a night of sky observ you can step into the form augustin pri for auth welsh ale
brecon beacon nat park pla y ffynnon cambr way 44 1874 624 437 namibrand nat reserv namib design may 2012 namibrand nat reserve's loc on the eastern edg of the namib desert has low humid and theref high night sky clarity
the closest town is maltahh 100 kilomet away
the shortest dist by road is 148 kilometers
the most interest object includ the cent of our milky way galaxy the megel cloud the zodiac light and planet say nil odenda ceo of namibrand nat reserve
under namibrand's exceiv view condit zodiac light and gegenschein ar visible
sossusvlei desert lodg has the best night view facility
you can ident deep-sky object with their 12-inch telescop aid by their resid astronomer
in the heart of the reserv wolw campsit lend out smal port telescop and provid guid train in bas astronomy
sossusvlei desert lodg c27 maltahh district 27 11 8094300 pack from n4950 445person per night wolw 264 61 230 616 pack from n3310 297person per night namibrand nat reserv 264 61 224882 mor the mag of namibia's night sky aorak mackenzy intern dark sky reserv new zealand design jun 2012 aorak mackenzy is privy to the best night sight of the southern hemisphere
you can see the auror aust the southern cross and the southern star
the reserv is the largest design by the id so far at almost 4300 squ kilomet on the sou island of new zealand
tens of thousand of visit each year tak the night sky tour at lak tekapo and mount cook with provid such as big sky stargaz and mt john night-time observ tours
the best view of the starry sky ar on night with no moon
wh the ful moon is out condit feel eery lik daytim say krist wilson an astronom at ear and sky lak tekapo
at tim the milky way can be seen stretching across from on end of the horizon to the oth he says
aoraki mackenzy intern dark sky reserv stat highway 80 64 3 435 1186 exmo nat park uk design octob 2011 exmo nat park was europe's first intern dark sky reserv when it was design in 2011
on the clearest night around 3000 star ar visible
th darkest ski in the uk ar march and april mak them particul good month for stargazing
dur lat sum you hav a good chant of see meteors
wimbleball lak has on of the best view of the night sky
it has unobstruct lakesid view and it dist from resid area leav the sky abov it near pristine
exmoor nat park 44 01398 323 665 mont-mgantic intern dark sky reserv canad design septemb 2007 mont-mgantic was the first intern dark sky reserv when it was design with silv tier stat in 2007
approximately 50000 peopl com to mont-megantic a year to apprecy the night sky phenomen say sbast gig head of commun at mont-mgantic
with the nak ey visit can see the milky way planet shoot star satellit andromed galaxy and sometim northern lights
with telescop moon crat galaxy planet nebula star nursery supernova planet nebula and star clusters
for the best stargaz the observ at the summit has publ telescop strong enough to see crat on the moon's surface
mont-mgantic intern sky reserv and astrolab 189 rout du parc notre-dame-des-bois qubec 1 819 888 2941 intern dark sky park blu ridg observ and star park nor carolin design febru 2014 thi new dark sky park is man by the mayland commun colleg which is build a custom 34-inch telescop and observatory
the equip wil be on the hil overlook the energyxchang sit and has a 360-degree view of the area
views of the milky way from thi sit ar simply stun say tod bush a photograph of the night sky
future observ her wil lik bask in it glow with the unaid eye
th telescop wil be the largest in the southeastern us ded to educ and publ outreach
the sit is fre for am astronom and the colleg hop to attract stargaz from around the area
mayland commun colleg blu ridg observ and star park 1 828 675 5541 northumberland dark sky park uk design decemb 2013 northumberland dark sky park is hom to britain's largest sky view stat kield observatory
when the sky is at it darkest in wint deep sky object lik the andromed galaxy ar vis with the nak eye
during sum you can see the milky way comet and meteors
regular program ar led by astronom at kield observ includ telescop workshop jupit night and famy astronom events
you can enjoy the best of hadrian's wal whil stargazing
the dark sky park is in the cent sect of the unesco world herit site
northumberland dark sky park 44 0 1434 605 555 kield observ black fel off shil pot 44 0 7805 638 469 chaco cult nat hist park new mexico design august 2013 at chaco you can stargaz among ant pueblo ruins
chacoan peopl observ the sam night sky almost 1000 year ago
with mor than 99 of the park a nat dark zon thos afraid of the dark bet bring a flashlight the reg to conserv the night sky stip no perm outdo lighting
the park hold regul ev and act includ archaeo-astronomy publ telescop view pueblo bonito ful moon walk and campfir astronomy
special ev ar org for phenomen such as eclips and met showers
chaco cult nat hist park 1 505 786 7014 x 221 7 per vehic or 4 per person valid for sev day dea valley nat park californ design febru 2013 dea valley nat park is the largest dark sky design are with a span of 13700 squ kilometers
the near pristin night sky has minim light impact from big city despit being in the vicin of las vega 190 kilomet to the southeast and los angel 460 kilomet to the southwest
death valley park rang lead night sky program and ev with astronom org dur the main visit season from novemb to april
mahogany flat campground is on of the highest area you can stay overnight
open between march and novemb the sit is 2499 met abov sea level on telescop peak the highest mountain in dea valley nat park
death valley nat park 1 760 786 3200 20 per vehic or 10 per person valid for sev day big bend nat park texa design febru 2012 big bend nat park is the northern hemisphere's southern-most intern dark sky park
we ar rel far sou in latitud and at least three of the four star in the southern cross and the southern star ar view her say david elkowitz chief of interpret partn and concess at big bend nat park
on a clear night you can see the cor of the andromed galaxy
around 2000 star ar vis as wel as met and planet mercury ven mar jupit and saturn
with an elev of mor than 1600 met chiso basin campground off prim night view against the chiso mountain range
bid bend nat park 1 432 477 2251 20 per vehic or 10 per person valid for sev day mor how to get america's most crowd nat wond to yourself headland intern dark sky park michig design may 2011 emmet county host vary ev to reconnect visit with the night sky and star lor of nor am indig cultures
monthly program ar fre and persist through rain snow and clear night skies
event includ introduc to night sky watch technolog nar guid to watch moon eclips and moon gaz picnics
during the an met show such as the quadrantid in janu the perseid in august and the geminid in decemb you can watch the fal star reflect in the wat of on of the gre lakes
the stretch of shorelin along lak michig mak the headland on of the best us stargaz destinations
headland intern dark sky park 1 231 348 1704 fre admit observ park geaug park district ohio design august 2011 mor than 8200 peopl visit observ park in 2013 for program and night view with astro-nats the park's astronom nat say sandy ward commun spec for geaug park district
the op field encirc by the planet trail off unobstruct view wher you can see the milky way and planets
you can view moon crat constel and nebula us the park's telescop or at the planetarium
observatory park 1 440 286 9516 hortobgy nat park hung design janu 2011 som of hortobgy nat park's best view and photo op of the night sky ar adjac to kilenclyuk hd the nin arch bridg the longest ston bridg in hung and a unesco world herit site
th park beg protect their dark ski as a mean of wildl conservation
last year we org sev 'star-walk program for expl the ev and nighttim nat beauty such as migr bird and star say istvn gyarmathy starry-sky park coordinator
pristine night ski ar part of region's history
hortobgy's tradit shepherd heavy rely on knowledg of star and constel to liv and work he adds
hortobgy nat park 36 52 589 000 clayton lak dark sky park new mexico design jun 2010 dur the day visit can scrutinize dinosa track on the ground
at night you can enjoy som of the darkest night ski in the country
the observ feat a comput telescop and remot tv monitor
stargazing group can view the night sky through the building's retract roof
unlike the expery of isol at dea valley visit her wil oft find themselv bump elbow with others
local astronom club and star party com to the park and observ to us the telescopes
clayton lak stat park 1 575 374 8808 5day per vehic goldend observ stat park washington design jun 2010 equip with on of the country's largest publ telescop goldend observ stat park has attract ten of thousand of night sky watch sint it op in 1973
you can tak guid tour or sky gaz independ at the observ atop a 640-meter-tall hil nor of goldendale
summer and wint program ar avail year-round
looking west dur autumn you can see saturn and ven with the nak eye
goldendal observ stat park 1 509 773 3141 10day per vehic zsel starry sky park hung design novemb 2009 nestl in the southwest hung woodland zsel starry sky park is on of the best plac in europ to see the zodiac light
the phenomenon can be seen best dur spring and autumn
you can follow a sky map or tak a guid on a star walk program
zselic starry sky park 36 1 375 4122 galloway forest park uk design novemb 2009 the scot dark sky observ sit on a hil on the edg of the galloway forest park
you can us the two main telescop to view deep-sky objects
outside of op ev you can on access the observ if you've book a sess or event
with the nak ey you can see the northern light and meteors
star form or stell nursery can also be seen without the us of equip but detail of nebula ar bet seen through a telescope
scottish dark sky observ off a713 just sou of dalmellington 44 01292 551118 op ev from 5 8 per adult sess from 10 16 per adult galloway forest park 44 01671 402420 mor scotland europe's wildest country cherry springs stat park pennsylvan design jun 2009 it's common to shar the astronom observ field with am astronom and fellow stargazers
more than 22500 visit cam to cherry spring stat park to sco the night sky in 2013
night program ar off every friday and saturday dur the sum and saturday in the spring and autumn
depending on the season you can see the constel of sagittari and cassiope among mor than 10000 stars
the vis is oft clear enough for the milky way to cast shadow on the ground
cherry springs stat park observ field from 4 per person nat bridg nat monu utah design april 2007 the crest of owachomo bridg form a window to mor than 15000 star and the milky way overhead
the dark canyon wal contrast against the bright starry skies
natural bridg nat monu had the darkest night sky the id had ev seen when it becam the first intern dark sky park
natural bridg has zero light pollut say rang gordon gower
when you view the night sky from nat bridg ther is no hum light visible
on the astronom rang program you can us the custom-built 165-inch newton telescop to view nebula galaxy star clust and planets
the guid ev dur the sum ar the park's most popular
natural bridg nat monu 6 per vehic or 3 per person valid for 7 day 1 435 6921234 provid germany's eifel nat park has a provid stat as an intern dark sky park
it wil be grant ful cert if mor than 90 of the surround commun improv their light reg by 2017