cant wil be no 1 killer
cnn in 16 year cant wil becom the lead caus of dea in the unit stat surpass heart diseas accord to a new report from the am socy of clin oncology
the numb of new cant cas is expect to increas near 45 by 2030 from 16 mil cas to 23 mil cas annually
this influx of new paty wil plac a big burd on a field of medicin already stretched by phys short and fin difficul say the report which highlight grow problem for cant car in the unit states
dr jeffery ward know thes issu well
when he join a commun oncolog pract in seattl it had three doctors
a few year lat the group merg with anoth pract and connect with a nat network of commun doct that en them to invest in new technolog and receiv group discount on cant drugs
in return they paid a perc of their practice's profit to the network
over tim the doct profit margin becam slimmer
they couldnt compet with hospit in the are for rady therapy and oth serv that would hav divers their pract and ins had the up hand in contract negotiations
it becam obvy as ward said that 0 of zero would be zero
so ward and his colleagu decid to leav the commun oncolog network and join a larg hospit system in seattle
nearly two-thirds of the smal oncolog pract survey said they wer lik to merg sel or clos in the upcom year accord to the oncolog group's inaug report the stat of cant car in america
and as commun pract disappear paty ar pay mor and travel farth for qual care
if you cant get car you cant get good car said am socy of clin oncolog presid dr clifford hud chief of breast cant medicin serv at mem slo ket cant cent and a profess at weil cornel med college
who immin glob cant disast ad to the burd wil be an increas in the numb of cant survivors
fifty year ago on a hand of minim effect tre for cant ex accord to the report
today ther ar mor than 170 fda-approved anti-cancer drugs
two-third of am now liv at least fiv year aft a cant diagnos up from about half in the 1970s the report auth write
survivors nee ongo car as they're at high risk for oth typ of cant and condit such as diabet cardiovascul diseas and osteoporosis
the afford car act wil also increas the nee for oncolog as mil of am get new cov by heal insurance
taking thes fut paty into consid the oncolog socy expect demand for oncolog serv to grow 42 by 2030
yet the numb of oncolog is expect to grow on 28 lead to a short of mor than 1400 physicians
a larg part of thi is becaus of the ag phys pop accord to the report
in 2008 the proport of oncolog old than 64 surpass the proport young than 40 for the first time
a larg numb of commun in cent and midwestern stat ar cov sol by thes old doctors
when they retir mor paty wil hav to travel farth to find care
th short of oncolog is a real problem said dr ot brawley chief med off of the am cant society
many smal pract act provid a lot of uncompens car to thos who do not hav ins or hav ins that doe not pay well
the report also highlight the nee to low cost for both doct and patients
right now the system is design to compens doct for how much they do rath than how wel they do it
th goe against the oncolog society's recommend which enco phys to avoid perform unnecess test and treatments
one of the reason that so many paty ar harm in medicin is they ar over-treated brawley said
how doct do harm drug pric ar anoth big concern
wh ward start pract the av cant drug cost 1000 per month
today he said the av is 10000 per month
if we dont begin to control thes pric in on way or anoth in 20 mor year the av cost of a cant drug wil be 100000
that's not sustain he said
twenty perc copay on 10000 per mon is not in the pocketbook for most of my patients
brawley said pric is on of the biggest reason ther is such a disp in cant outcom research show min ar mor lik to develop cant and mor lik to die from cancer
to comb som of the issu rais in the report and improv paty car the socy is work on sev project involv big data
these project wil help phys distil mass volum of dat into mean inform accord to the report authors
shopper hav amazon
students hav google
oncologists wil hav cancerlinq
medicine has lag behind the rest of socy in adopt and benefit from thes remark and ubiquit technolog improv hud said
cancerlinq is an electron heal system that wil collect and analys dat from mil of paty and provid feedback to provid in term of standard of car and best practices
it goal hud said is to prev mistak bef they happen
i'd rath hav a doct who avoid mistak than on who learn from them he said
the oncolog socy said it expect to rol out som compon of the system in ear 2015
most cant cas ar prev