josh hardy fac 'long road to recovery'
cnn the drug is fin in josh hardy's system but his fath say his ail son is stil look at a very tough road
josh's par got what they'd been pray for thi week a chant to get medicin that could help their 7-year-old son survive
th chimerix pharmaceut company said tuesday that josh would receiv medicin that doct hop wil help him
he got his first dos of the drug brincidofovir on wednesday
the company had prevy deny cal from the famy to giv him the drug argu that spend the tim to help josh and oth lik him would slow effort to get the drug on the market
the boy's story drew nat at as his par and support push the company to chang it mind through onlin and med campaigns
josh has a long road to recovery tod hardy josh's fath told cnn in an e-mail thursday
he said his son has stop get wors that he was detery last week and now he's not
josh is expect to tak the drug for at least 12 weeks
he stil isnt tak any food or drink by mou and his 5-year-old broth jud is purpos tort him by drink carton aft carton of chocol milk that's avail in the icu break room hardy said
josh's journey beg when he was diagnos with a rar form of kidney cant at 9 month old
over the year cant turn up in his thym lung and bon marrow and each tim josh beat it
but a bon marrow transpl left josh without much of an immun system and in febru doct diagnos him with an adenovir that spread through his body
now he's in crit condit in a memph ten intend car unit as the vir rav his body
josh is in heart and kidney failure
a facebook pag ded to the onlin campaign to help josh get the medicin post a photograph of the boy along with the mess pleas pray that the drug is as effect in comb thi vir as we hope
cnn's dan ford and catherin e shoichet contribut to thi report