wesley univers stud alleg rap sue fraternity
cnn a wesley univers stud who say she was rap in front of onlook at a wild out of control camp fratern party has fil a lawsuit against xi chapt of psi upsilon 11 of it memb and the alleg assail accord to court documents
cabri chamberlin then a freshm said she was rap by anoth stud last may at the xi chapt of psi upsilon fratern hous in middletown connecticut at a pledg strip show say the suit which was fil tuesday in a connecticut fed court
cnn doe not us ident victim of sex assault but has don so in thi cas becaus the wom want to mak her nam public
i'm process in thi cas with my real nam instead of jan doe becaus as the victim of a hein viol crim i've don noth wrong and hav noth to be asham of chamberlin said in a stat provid by her lawyer
i cant ev describ the pain of being rap or how much it alt a lif and no oth person should ev be forc to hav that experience
i hop my expery and lawsuit wil cre chang that protect others
at the party the lawsuit say many und and extrem intox young peopl dant with nak pledg and spil alcohol throughout the area
chamberlin who has tak a leav from her study said she becam extrem uncomfort put on her jacket and attempt to leav when a mal stud pick her up from behind and rap her in the pres of num oth accord to the lawsuit
wesleyan publ saf off then took her to a nearby hospit wher a diagnos of sex assault was docu the lawsuit says
psi upsilon fratern tak al report of risk man viol espec thos with regard to sex assault very sery tom fox execut direct of psi upsilon fratern said on the fraternity's website
w ar cur investig the incid and gath furth information
after an intern investig the univers expel the alleg perpet and impos sanct against the fratern and memb accord to a stat by wesley presid michael s roth
the stud nam in the lawsuit who has not been charg crimin did not return cal seek comment
middletown pol confirm that they respond to a sex assault complaint from the psi upsilon fratern hous on may 4 2013 spokeswom lt heath desmond said
the investig is ongo and no charg hav been fil she said
desmond said pol wer hav difficul find wit and urg anyon who attend the party from may 3 into may 4 and may hav wit anyth to cal police
th lawsuit say the fratern contract demand self-governance from wesley relinqu the publ saf and hous serv the univers gen provid to students
the fratern alleg fail to adequ provid it own sec and the defend fail to train themselv in saf and risk man issu includ sex abus prev haz and the misus of alcohol accord to the lawsuit
chamberlin's lawy dougla fierberg said that becaus the fratern set itself apart from the univers off from the university's depart of publ saf can ent the fratern on in exig circumst or when spec ask to com in
this lawsuit seek to hold thi fratern respons for it gross mism which it doe und the guis of self-management fierberg told cnn
fraternity self-management has hist prov itself to be flaw and dangerous
women hav been rap becaus of thi mismanagement
people hav died becaus of thi mismanagement
and thi victim wil hold the fratern respons for it tradit of dang mismanagement
wesleyan univers would not com on the fraternity's arrang with the depart of publ saf but roth's stat acknowledg that the university's fratern hav som autonomy
all hav seen increas scrutiny ov the past few year roth said of fraternities
we intend to foc our at on improv the saf of thes spaces
wesleyan univers was not nam in the lawsuit
on behalf of the univers commun i want to express our hor at thi sham assault roth said in the statement
sexual viol wil nev be tol on our campus
sexual viol on colleg campus is a nat problem and it's import to rais aw about thi issue
at wesley we ar commit to car for surv vig pursu perpet and cre a posit camp clim in which sex viol and misconduc hav no place
chamberlin has tak a leav of abs from the univers sint the attack and is receiv intend counsel try to pul her lif togeth her lawy said
chamberlin is seek 10 mil in dam the lawsuit says
in 2012 a wesley stud sued the univers and anoth fratern which wesley no long recogn as a stud org aft she said she was rap in it frat hous two year before
th fratern had garn the on-campus reput as the rap fact accord to the lawsuit
her assail plead guil to assault and unlaw restraint court pap said
the cas was settl in court-ordered medy in august 2013
cnn's haimy assef contribut to thi report