can a photo comb hung 
cnn when you think about the im typ assocy with hung a recr of the mad hatter's tea party from al in wonderland might not spring to mind
but on florid nonprofit is us recr scen from popul movy mus and tv show to get peopl talk about poverty and hunger
the pensacol group appetit 4 lif provid food to childr the eld peopl with dis and termin il patients
looking for an edgy way to rais aw about poverty and hung in the loc commun the group turn to cnn ireport jam amerson a photograph and long-time friend of many of the board memb of the nonprofit
amerson conceiv the commun art project appetit 4 art which combin food with im of icon film mus and tv show to get peopl talk about hung and poverty
images lik mary antoinet sav bit into a blood-r slic of red velvet or marilyn monro try to hold down a whit dress of splashing milk ar meant to provok peopl to quest the mess behind them said amerson who serv as cre director
i want the im to first seem obvy but then get the view to stop and tak a second deep look to connect the purpos behind the photo he said
amerson was inspir by the glob art project insid out start by par photograph jr who want to get peopl talk about soc issu lik poverty hung and homeless through larg wal postings
with a grant from the gre gulfcoast art fest amerson and a smal group of volunt photograph and model wer abl to afford the prop food set and print cost nee to cre the im of lav decadence
th shoot took sev week to org and produce
they most chos scen from film that already had food in them but took cre licens with the im inspir by am beauty dext and the sev year itch
the collect isnt intend to portray hung he said but to rais aw about the organization's efforts
the pict wil be display on the sid of the appetit 4 lif build in ear april for four week bef they travel to loc gallery start with the ann lam cent for vis art at pensacol stat college
whil the im ar meant to rais aw mor than money appetit 4 lif has receiv off from peopl interest in buy the photos
the org is consid mak the im avail to purchas with al of the process going to support the organization
bill shor found and ceo of the nat hung nonprofit shar our strength said org nee to get cre to get peopl to pay at to hung and poverty peren issues
data speak to a person's mind emot speak to their heart shor said
creativity is the bridg between the two
the mor cre the commun the mor lik peopl wil not and be wil to giv of themselv