unit off fre streaming tv and movies
cnn tir of hokey in-flight movy or spotty directv connections
united airlin is ad an opt for watch tv dur flight that let passeng stream cont direct to their laptop iphon ipad or ipod touch for free
th airlin annount the new entertain system in febru and wil rol it out on us flight start in april
united wil preload 150 movy and 200 tv show onto an on-board system
passengers with compat dev wil be abl to stream direct from a serv on the plan so there's no nee to pay for in-flight wif serv and the airlin wont hav to worry about an entir airpl of peopl gobbl up bandwid whil binge-watching
united has chos a combin of new and class cont includ popul tv show downton abbey and netflix's hous of card to start
eventually the aircraft wil swap in fresh movy and episod every mon so frequ fli dont run out of thing to watch
the program doe hav som limitations
the most not is that it on work with appl smartphon and tablet run io 6 and abov for the tim being
to watch show on an io dev passeng must download the off unit app
android us ar out in the cold unless they hav a laptop handy but unit is work on ad support
we expect to off the sam serv for us of android mobl dev lat thi year said a unit spokesperson
passengers can watch the movy and show on whil in the air but unit plan on mak it work from gate-to-gat to reflect rec chang in mobl dev policies
late last year the faa chang it policy to allow passeng to us mobl dev bef and dur takeoff and land at the discret of the airlines
on comput the streaming work with window comput run window xp and window 7
it requir the most rec vert of the chrome firefox or internet expl browsers
mac laptop must hav os x 106 or high and us safar chrome or firefox
the brows must run flash 103 or higher
f sec reason som of the cont can on be view with a spec brows plug-in which can be download in-flight
the first plan to off the feat wil be the airb a319 and a320 the boe 747-400 and som boe 777-200s
to decid if you nee to download al three season of veronic mar bef get on a cross-country unit flight check to see wheth the new in-flight mobl streaming serv is off by look at the list of am for yo flight