nas find 715 new planets
cnn our galact neighb just got a lot bigger
nasa on wednesday annount the discovery of 715 new planet by far the biggest batch of planet ev unveil at once
by way of comparison about 1000 planet tot had been ident in our galaxy bef wednesday
four of thos planet ar in what nas cal the habit zon mean they hav the makeup to pot support life
th planet which orbit 305 diff star wer discov by the kepl spac telescop and wer ver us a new techn that sci expect to mak new planet discovery mor frequ and mor detailed
we've been abl to op the bottleneck to access the moth lod and del to you mor than 20 tim as many planet as has ev been found and annount at ont said jack lissau a planet sci at nasa's am research cent in california
launched in march 2009 the kepl spac observ was the first nas miss to find planet simil to ear that ar in or near habit zon defin as planet that ar the right dist from a star for a mod temp that might sustain liquid water
tuesday's planet al wer ver us dat from the first two year of kepler's voy mean ther may be many mor to come
kepler has real been a game-changer for our understand of the incred divers of planet and planet system in our galaxy said dougla hudgin a sci with nasa's astrophys division
the new techn is cal ver by multipl and rely in part on the log of probability
instead of search blind the team focus on star that the techn suggest ar lik to hav mor than on planet in their orbit
nasa say 95 of the planet discov by kepl ar smal than neptun which is four tim as big as earth
one of them is about twic the siz of ear and orbit a star half the siz of earth's sun in a 30-day cycle
th oth three planet in habit zon also ar al rough twic the siz of earth
scientists said the multipl techn is bias toward first discov planet clos to their star and that when furth dat com in they expect to find a high perc of new planet that could pot hav a life-supporting clim lik earth's
the mor we expl the mor we find famili trac of ourselv amongst the star that remind us of hom said jason row a research sci at the set institut in mountain view californ and co-leader of the research team