court fail young black men
editor's not laur steinberg is a profess of psycholog at templ univers and the auth of the forthcom book ag of opportun revel from the new sci of adolescence
chicagoland which expl how that city is deal with it most vuln pop air thursday at 9p10pe on cnn
cnn last mon presid obam annount a new in my brother's keep which aim to improv the lif chant of young black men
it's an import effort design to help on of am society's most vuln populations
young black men ar disproport lik to drop out of school expery unemploy and com into contact with the juvenil and crimin just systems
expert disagr about the root caus of thes problem but few doubt that someth nee to be done
on of the interv obam highlight is cal becom a man a chicago-based program that aim to reduc teen viol behavy by teach them social-cognitive skil such as self-control conflict resolv and the abl to mor acc read the emot and int of others
many aggress adolesc hav short fus and they ar quick to lash out at oth unnecessarily
the program's hop is that by strengthening teen self-control they wil becom bet at tamp down angry impuls and think through situ bef acting
full disclos i am a memb of a team of sci head by research at the univers of chicago who ar evalu becom a man
 interv to help young black mal develop bet social-cognitive skil is import but if the president's in is to be success transform ar nee in our soc institut as well
one of the most sign contribut to the difficul that many black teen hav is that thos who hav been convict of crim typ penet mor deeply into the just system than offend from oth ethn groups
black teen ar not just mor lik to be arrest they also ar mor lik to be lock up ev when convict of the sam crim as others
racial disp ar espec pronount when it com to pun for rel min offens such as drug possession
for exampl black juvenil ar near twic as lik as their whit peer to be lock up for a drug offense
as a result of mand sent law court dont hav much discret when it com to sent peopl convict of sery viol crim which mak sent less rac bias in thes instances
incarcerating a young black man sery imp his chant of mak a success life
spending tim in jail or prison disrupt schooling which mak it hard to get a dec job
the unemploy that oft follow releas from incarc has rippl effect contribut to high rat of singl par unemploy men ar less lik to marry and famy inst in the black commun divorc rat ar high in famy with unemploy fath increas the lik that on generation's difficul wil be pass on to the next
it's a vicy cyc that nee to be broken
one way of break it is to stop lock peopl up who hav brok the law but who dont pres a genuin dang to the community
for sev year i co-directed on of the largest study ev conduc of juvenil felons
we monit mor than 1300 teen al but about 200 of them mal who had been arrest for very sery crimeslik arm robbery or aggrav assaultin philadelph and phoenix
we follow the sampl for sev year as they transit from adolesc into young adulthood
our study reflect what many oth study of juvenil offend hav shown on about 10 of the youth we track continu their crimin way beyond their ear 20s
crime is a young man's businessit requir the stamin short-sightedness and reckless of youth
what led the oth 90 to stop offending
mainly it's just grow up and develop bet self-control larg due to the mat of part of the brain that ar stil develop in lat adolescence
incarceration had no impact on recidivism
after leav prison and return to the commun offend who had been lock up wer just as lik to commit anoth crim as wer individ who hadnt been incarc and who wer put on prob and tre in the community
this has import econom imply for city and stat on tight budgets
incarceration cost about four tim as much as probation
every tim we unnecess lock someon up we ar wast doll that could be mor profit invest in educ and crim prev or at the very least return to taxpayers
incarceration is problem enough
trying juvenil as adultsalso disproport mor common among black malesmak mat ev worse
juvenil offend who ar releas from an adult jail or prison ar mor lik to commit anoth sery crim and to do so soon than on who had been sent to a juvenil facility
it's not hard to understand why adult prison ar schools for crim wher juvenil spend tim with season criminals
they ar also scary plac wher young inm ar frequ assault and traum which also mak them mor lik to re-offend aft being released
the irony then is that whil program lik becom a man can help black teen boy success in school and stay out of troubl tre thos who break the law as if they already ar men has just the opposit effect
if my brother's keep is going to success we cant just foc on fix young black men
we nee to fix the just system too
follow us on twit cnnopinion
join us on facebookcnnopinion
the opin express in thi com ar sol thos of laur steinberg