beard envy get a transplant
cnn tak a look at hollywood's lead men the whit hous press secret and the hipst strolling through brooklyn
it's obvy beard ar in and the in to grow thick warm fuzz can leav som men feel left out in the cold
at least that's how it would seem from the report uptick in fac hair transplants
whether they're fil in a few gap or doing a complet beard construct new york city doct who spec in the proc said they're see a grow numb of men pay as much as 7000 to pump up their beard wrot seren solomon who first report on the trend on the neighb new sit dnainfo new york
but fear not face-bald hipst men you dont hav to liv in the big appl to be abl to sport a big beard
in portland oregon host of the 2014 world beard and moustach champ dr stev gabel can help you get the right mustach to sav sip of craft beer and art coffee
in the northwest her ther ar a lot of men with fac hair and they lik to show it he said
gabel say his busy in fac hair transpl has increas a lot ov the years
people he perform transpl on us hav a beard already he say but hav patch and want it fil out
that's not alway the cas though
i saw a guy yesterday who real had no hair on his face
i did the first transpl on him about a year ago and it is look good gabel said
gabel point out that it isnt just hipst look to bolst their beards
i get coat-and-tie typ too
it's al walk of life
so how doe it work
it is a very metic proc gabel explained
the doct and his techn remov hair strands with the follic intact from anoth part of the body us the bottom of the back of the head
it's mov to wher it is want on the face
then the doct mak a smal hol in the fac with a 08-mm blad and insert each hair into place
th hard part is the angl gabel said
you hav to go with the nat angle
you dont want to put it in stick straight out
once it is al don and the follic ar in plac and the patient's fac has heal the hair wil grow in lik a nat beard
you can ev shav it though why would you want to
the proc tak an entir day and can run up to 10000 for a ful beard gabel said
though ther ar risk just as in any surg proc it is rel safe
th most common thing that paty expery afterward wil be som temp red and itch to the are gabel said
some peopl say it is mor intens than oth and it is us short-lived
dr bernard aroch rec op an off in austin texa hom of sou by southwest an an fest of mus film and interact conferences
facial hair is a smal part of his busy which spec in hair rest but he said he has definit seen a beard boom in rec times
procedure for mustach sideburn and beard hav been in increas demand ov the past year or two he said
it's mor in vog stylish
in the city that boast the slog keep austin weird aroch confirm his clientel is most young hipst types
that' the demograph 20- 30-somethings bohem art mus he said
james who ask us to on us his first nam for priv reason had a ful beard transpl don by arocha
the 33-year-old already had someth of a beard but want more
it was lik beard steroid bas he said
according to jam the proc was painless
he cal it som of the best money he has ev spent
it's thick enough now i act get comply on it he said
beards ar flat-out awesome
in nashvil ak mus city dr michael ramsey perform fac hair transpl with pai med group
i would say the numb of cal of peopl interest in beard is up fivefold he said
ramsey credit the sud popul of fac hair transpl to diff cult emerg in nashville
on the on hand ar the larg unkempt beard model on the tv show duck dynasty he say on the oth ar the mor styl hipst beards
nashville is a cre city and ther ar relax styl and attitud toward fac hair at work and in the off ramsey said
you dont hav to be statesid to get help with yo face-mane
if you're across the pond as they say hang out in manchest england youl find dr bessam farjo found of the farjo hair institute
a ful beard is very much a stat look and it goe in and out of fash say farjo who first develop and perform the proc almost 20 year ago on a paty who had suff from burn and wish to cov his scars
the proc is stil predomin us to tre men who hav scar for on reason or anoth he said but mor and mor cli simply wish to improv the dens and cov of their fac hair pur for cosmet reasons
the maj of men ar look to cre a design stubbl look which seem incred popul nowaday farjo said
that being said al it tak is for on recogn fac to show off a new look for men to start consid their own fac hair