their germ ar now our germs
editor's not dr tom fri is direct of the cent for diseas control and prevention
on thursday the unit stat join mor than 25 nat and intern org to launch the glob heal sec agend an effort to accel progress toward a world fre of infecty disease
cnn the world is smal and peopl ar mor mobl than at any tim in history
this mak it easy than ev for what's hap anywh on the glob to harm am health
 her ar fiv way diseas in oth country pos a threat the flu could threaten millions
even in a mild year for flu in the unit stat alon ther ar thousand of death hundr of thousand of hospit and bil of doll in produc losses
in a pandem mil of peopl worldwid could be killed
h7n9 influenz also known as bird flu is spreading in chin though fortun it has not mut to becom an infecty diseas outbreak that could threaten the heal of peopl around the world
antibiotic resist is on the rise
antibiotic resist just might be the most urg heal threat fac us now
the nightm strain of bacter known as cre carbapenem-resistant enterobacteriacea aros abroad and was introduc to on stat in the unit states
now it's in at least 44 states
it can resist al or almost al antibiot kil many of the peopl who get it in their blood and spreads it resist cap to oth bacteria
the world heal org estim multidrug-resistant tuberculos already has infect a half a mil peopl across the globe
a nightm heal scenario we can stop diseas dont respect borders
going abroad can expos travel to mor than new cult and once-in-a-lifetim experiences
more than 1500 us travel get malar every year and the numb ar increasing
yellow fev is spread by mosquito and caus mor than 30000 death worldwid each year prim in trop area of afric and latin america
people com back from safar might bring back mor than just pict they could find themselv fac afr trypanosomias bet known as sleep sick transmit by the tsets fly found on in rur africa
foreign diseas ar now domest threats
we think of parasit diseas as risk to travel but they harm peopl her at hom as well
for exampl chaga diseas is a chronic infect gen acquir by peopl in rur area of latin americ but about 300000 peopl now liv in the unit stat hav thi disease
toxoplasmosis is a parasit diseas common in the trop that infect mor than 60 mil peopl in the unit states
while the immun system us keep the parasit from mak peopl sick it can caus dea attribut to foodborn illness
emerging infect what's the next hiv
mosquito-borne diseas such as west nil vir dengu and chikunguny infect hundr of thousand of peopl each year and ar spreading globally
in the past few year we'v seen glob outbreak of ebol and oth dead vir hemorrh fevers
5 heal challeng for 2014 ther ar many diseas out ther that we dont ev know about
our new effort can prev them from becom epidemics
that' why cdc partn with nat al ov the world to detect and respond to diseas outbreaks
together we respond to mor than 250 outbreak in 2013
no singl country can deal with thes heal threats alone
cooperation between country has tremend impact in ear detection
early detect of a singl cas of ebol vir in 2011 led to an immedy respons and the diseas was stop in it tracks
previ simil outbreak wer larg and spread rapid through commun there
cdc is help country around the world strengthen their abl to prev avoid catastroph and epidem detect threats ear and respond rapid and effectively
stopping outbreak wher they occ is the most effect and least expend way to sav liv at hom as wel as abroad
and it's the right thing to do
that's why we annount thursday that the unit stat through the work of the cdc and the depart of agricult stat and defens has commit to coop with at least 30 partn country to bet prev detect and effect respond to infecty diseas threats bet protect at least 4 bil peopl around the world includ the unit stat from threats
how to prev the next pandem and we hav cal on partn country to work togeth so that effect prev detect and respons ar pres in every country around the world
this year cdc and the depart of defens hav pledg 40 mil to expand to 10 addit country in addit to the pilot project in ugand and vietnam
president obam wil request an addit 45 mil in 2015 to accel progress around the world
it's an ess step in strengthening glob heal sec that wil protect am strengthen our nation's glob partn and increas heal sec capac around the world
helping oth country mak thos country and the unit stat safer
the most infecty of al infecty diseas