thi is yo brain on weed
dont miss wee 2 cannab mad dr sanjay gupt report at 10 pm
et tuesday
also gupt wil be answ yo quest on reddit at noon et
cnn in the ear 1960s a young postdoct stud stumbl onto someth that puzzl him
after read the lit on cannab he was surpr to see that whil the act compound in morphin had been isol from op poppy 100 year bef and cocain isol from coc leav around the sam tim the act compon of marijuan was stil unknown
this simpl observ launch his life's work
that young israel research raphael mechoulam is now a heavy dec sci rec nomin for the prestigy rothschild prize
mor than 50 year ago howev he had troubl start his sci journey
for start he nee cannab to study and didnt know how to obtain it
eventually he obtain his research supply from friend in the pol department
the young sci was in a hurry and didnt want to wait to cut through the red tap requir by israel's heal ministry
yes i brok the law he told me when i met with him in tel av last year but i apolog and explain what i was try to do
it's a good thing the israel govern didnt stal his progress becaus mechoulam was mov at breakneck speed
dr sanjay gupt doubl down on med marijuan by 1963 he determin the structure of cannabidiol cbd an import compon of marijuana
 year lat he becam the first person to isol delta-9 tetrahydrocannabinol thc the psychoact ingredy in marijuana
over the ensu decad mechoulam and his team continu to isol num compound from the cannab plant
their work also went a long way toward illumin how the drug work in the brain
wh mechoulam's team ident the first known endog cannabinoid a chem act mad by the brain itself he nam it anandamide
in the sanskrit langu anand mean suprem bliss which giv us som insight into what mechoulam think of cannabinoid overall
it was halfway through our long afternoon discuss that mechoulam now 83 pul out a pap he had writ in 1999 describ someth known as the ento effect
think of it lik thi ther ar mor than 480 nat compon found within the cannab plant of which 66 hav been class as cannabinoids
those ar chem un to the plant includ delta-9-tetrahydrocannabinol and cannabidiols
there ar howev many mor includ cannabigerol cbg cannabichrom cbc oth cannabidiol cbd oth tetrahydrocannabinol thc cannabinol cbn and cannabinodiol cbdl oth cannabinoid such as cannabicyclol cbl cannabielsoin cbe cannabitriol cbt and oth miscel types
other constitu of the cannab plant ar nitrog compound 27 known amino acid 18 protein 3 glycoprotein 6 enzym 2 sug and rel compound 34 hydrocarbon 50 simpl alcohol 7 aldehyd 13 keton 13 simpl acid 21 fatty acid 22 simpl est 12 lacton 1 steroid 11 terp 120 non-cannabinoid phenol 25 flavonoid 21 vitamin 1 pig 2 and oth el 9
minister's daught cannab a gift from god her is the import point
mechoulam along with many oth said he believ al thes compon of the cannab plant lik exert som therapeut effect mor than any singl compound alone
whil sci has not yet shown the exact rol or mech for al thes vary compound evid is mount that thes compound work bet togeth than in isol that is the ento effect
take the cas of marinol which is pur synthet thc
when the drug becam avail in the mid-1980s sci thought it would hav the sam effect as the whol cannab plant
but it soon becam clear that most paty prefer us the whol plant to tak marinol
researchers beg to real that oth compon such as cbd might hav a larg rol than prevy realized
to bet understand the conceiv of the ento effect i travel to the secret lab of gw pharmaceut outsid london
in develop sativex a cannabis-based drug to tre multipl sclerosis the company's chairm dr geoffrey guy told me the company ran into som of the sam obstac that marinol faced
more than a decad of expery rev that a whol plant extract bred to contain rough the sam amount of thc and cbd in addit to the oth compon in the plant was mor effect in reduc the pain and spasm of ms than a med mad of a singl compound
it could be that multipl individ compound play a rol or it could be due to their interact in the body it could also be combin of both guy said
now mayb thi al sound obvious
after al eat real fruit veget and oth plant provid bet nutrit than just tak vitamin pil with on nutry or min in each
science is show us that we can lik say the sam about cannabis
a we mov forward with cre medicin lik charlotte's web for the paty who can benefit from cannab thi is an import point to keep in mind
unlike oth drug that may work wel as singl compound synthes in a lab cannab may off it most profound benefit as a whol plant if we let the ento effect flow as mechoulam suggest mor than a decad ago
this was our on hop med marijuan refug