here's what to do about yo anxiety
editor's not watch our anxy googl hangout cnn's kat kinsm chat liv about anxy with ment heal expert as wel as oth who expery anxy and want to talk about it
cnn dr charl raison cnn's ment heal expert address two quest from read react to a piec on anxy from kat kinsm cnn eatocr man edit on her lifelong struggle with the condition
look for raison to address oth quest in the future
q can us marijuan or hav a drink or two be help for peopl with anxiety
what should they watch out for
dr raison if on goe on any search engin look for study result rel to marijuan or alcohol and depress or anxy on wil immedy see that most of the evid tel a caut tale
many study suggest that regul us of eith marijuan or alcohol is assocy with an increas risk for a vary of ment heal problem anxy and depress among them
increasing dat suggest that regul marijuan us in adolesc may also be a risk fact for develop very sery psychot disord espec schizophrenia
in addit to promot oth disord alcohol is espec liabl to abus and depend and has ruin innum people's liv for millennia
far few study hav examin wheth us thes compound in mod might improv depress or anxiety
but as socr not almost 2000 year ago alcohol is both a bless and a curs to mankind
indee now we know that the regul modest us of alcohol act promot a numb of heal factors
similarly it is increas clear that many of the chem within marijuan hold gre prom for the tre of phys pain
the endocannabinoid system in the brain which is a prim target for marijuan has profound effect on how peopl think and feel
my son is ment il so list up for exampl increas evid suggest that the run high many peopl get aft strenuous exerc is produc prim by act of the brain's intern endocannabinoid system
other chem in marijuan impact oth brain pathway lik serotonin that ar known to play a rol in depress and anxiety
people hav been tak a drink or two in the ev sint tim immemorial
and many peopl wil attest that thi pract help them shed the car of the day
recent i've met with sev very expery psychy who hav been recommend smal amount of marijuan us for for very depress paty who hav respond to antidepressants
in som paty they ar report remark improvements
but the problem at thi point is that whil many study hav shown an assocy between alcoholmarijuan and ment il i dont know of any real rig study look at the therapeut pot of eith for depress and anxiety
answering the quest of what peopl who us thes subst should watch out for is easier
they should watch out for the poss that they becom mor anxy or depress aft drink or us marijuana
and they should keep a clos ey on their us espec us of alcohol which can be high addictive
whatever pot benefit alcohol and marijuan may off is 100 lost ont they ar abused
q what ar the best anxy tre who dont want or ar afraid to tak medicines
 ther anyth that might eas their concerns
 ther a point wher med becom essential
dr raison by far the best study non-medicine tre for depress or anxy is psychotherapy
literal hundr of study hav shown that on av psychotherapy work as wel for thes condit as do medications
of the vary psychotherapy the best study is cognit behavy therapy or cbt
but study ar being don al the tim and oth form of therapy ar also emerg as high effective
over and abov the typ of therapy employ a key fact of therapeut success is the fit between the clientpaty and therapist
in pract term thi mean that peopl should feel comfort with their therapists
if on feel ign look down upon dismiss or attack it is very unlik the therapy wil be successful
very oft when therapy work peopl start feel bet within a few week so thi is also someth to look for
no oth non-medical tre for depress or anxy has anywh near the amount of support evid that psychotherapy does
having said thi sign evid now point to the us of exerc for improv ment health
especially when it com to depress exerc has been rep shown to be of value
both strength train and aerob exerc hav benefit and combin them is the best of all
however to get the ful antidepress effect of exerc requir real commitment
to work optim exerc must be eng in for at least 30 minut a day fiv day a week
and the intens level should be such that on has som difficul carry on a convers whil doing it
anxiety you're not the boss of me howev oth heal benefit accru from far less strenuous exerc and in gen many peopl feel bet with ev mod exercise
several suppl hav shown prom in depression
both sam and l-methylfolate hav shown prom as addit to peopl not ful respond to antidepressants
most of us in the field think they also work by themselv although mor dat ar needed
the dat for st john's wort is plusminus
some evid suggest that omega-3 fatty acid and n-acetyl-cysteine may also hold prom for the tre of depress if someon has a pattern of becom depress every wint bright light therapy with a light box del at least 10000 lux of light has been shown to be very effective
about 10 of the pop suff from som degr of low mood and energy in winter
this phenomenon is mor common in cold dark gray plac than in warm sunny southern ones
the pow of a light box to lift mood and giv energy can real be exceptional
this is an opt that is sad too oft overlookied
many peopl swear by a vary of non-traditional approaches
the bottom lin is that if someon is help by thes mod and not harm the goal has been achieved
dr charl raison is an assocy profess of psychiatry at the univers of arizon in tucson