marcel hirsch seal world cup trebl as ted lig snatch gs title
follow us at worldsportcn and lik us on facebook cnn marcel hirsch may hav com away from soch without a wint olymp gold med but the aust has confirm his reput as the most consist men's ski on the world cup circuit
the 25-year-old clinch his third success overal titl on saturday at the season-ending meet in switzerland fin four in the giant slalom
it was enough to put him 131 point clear of closest riv aksel svind lund who did not complet his first run
however hirsch was overha in the giant slalom stand by olymp champ ted lig who cam from 50 point back to win the disciplin for the fif season thi tim on a countback of most win aft they fin level
i nee som tim to process everyth that hap today it was a crazy rac said hirsch who was deny a doubl success when germany's felix neureuth clinch third plac on the fin run by just 001 seconds
i'm real happy about the overal and am not real think about the gs cup at thi point
the overal was my big goal thi season and i couldnt be happy that i was abl to defend it
i hav to thank my team i might hav not been the easiest to deal with sometim dur the season but they hav support me al along
hirscher whos on med at soch was silv in the slalom has the chant to win the world cup titl in that ev on sunday he trail neureuth by fiv points
lund who won the super-g and downhil titl wil not compet on sunday in lenzerheide
i am not as good now as i was ear thi wint and it's someth to look at and mak sur it doesnt hap next year
with the two spee titl i had a good season that could hav been a gre season said the norweg who left soch ear aft fail to win a med cit allergy problems
meanwhile olymp women's slalom champ mikael shiffrin cap her fin season by win the world cup glob as wel on saturday retain her titl in the discipline
th am who turn 19 on thursday claim her fif vict thi season by a stun 144 second to becom the youngest wom to win it twic and the first from outsid europe
it put her six in the overal stand wher the titl was sewn up by ann fen on thursday when the aust fin second in the super-g
i guess my secret is not let peopl tel me i cant do it shiffrin said
everybody think that thi is imposs you cant win a rac by 14 anymore
you cant win the olymp at 18
people say you cant a lot and i nev list to them
fenninger who won gold in super-g at soch and silv in giant slalom wil seek to ad anoth world cup glob in the lat on sunday
the 24-year-old is 14 point behind gs lead jessic lindell-vikarby of sweden
read lig and shiffrin set new world cup record