opin israel abba fac 5 real on peace
aaron david mil is a vic presid and distinct scholar at the woodrow wilson intern cent for scholars and was a middl east negoty in democr and republ administrations
follow him on twitter
cnn mahmoud abba the palestin presid who wil sit with us presid barack obam on monday to discuss the stateand the fate--of secret of stat john kerry's peac process is a good man and most lik the best partn for peac negoty that washington thi israel govern or any oth is lik to have
he's rat enlight and a lead who eschew both viol and the dream that somehow sometim the arm struggle or demograph wil del palestin their state
but there's on on pesky problem und cur circumst he cannot del his sid of a comprehend peac agr with israel
here's why
the palestin consens abba is in a bind
he's trap by tradit palestin negoty posit and a nar that is almost imposs to alter
these posit includ jun 1967 bord with min territ adjust a capit in east jerusalem sec arrang that dont suck every bit of sovereignty out of palestin stat and an acceiv answ to the quest of what to do about the volatil issu of right of return
to diverg sign from them would end his polit viabl and perhap his life
even the lat palestin lead yass arafatwhos pow auth and legitim confer som discret and flexibility-- wouldnt agr to anyth short of thi consensus
i ont heard araf remark at the camp david summit you wont walk behind my coffin
and abba has littl of arafat's street cred
he is head of the palestin auth and the palestin lib organization's execut commit but is mast of none
not enough urg the ide that you could reconcil thi palestin consens with benjamin netanyahu's bottom linesassum you could ident them-- is fantastical
and his self-image is not to becom the midw or fath of a palestin stat bas on abba requir or nee it is to wat them down with us help
even then the ide that he's prep to yield to abba on bord or jerusalem is high improbable
th hist of peacemak on the israel sid is to be sur a hist of transform hawk see menachem begin yitzhak rabin ehud barak ehud olmert
but netanyahu is diff and circumst hav changed
the reg is in turmoil and ir is his real priority
there is neith enough pain nor prospect of gain for him to urg mak thi deal
divided palestin hama has been gre weakened
the oust of egypt's moham morsy turk prim min recep tayyip erdogan's troubl and hama nee to dist itself from syr hav block it options
but between fatah and hama the palestin nat mov is stil bad divid and resembl a kind of palestin noah's ark ther ar two of everyth statelet sec serv patron constitut and vis of what palestin is and ev wher it is
the real problem is that any recont of the two fact wil lik furth hard palestin posit cre a tradeoff intern peac in the palestin rank but mor tend with israel and prob the unit stat too
and yet unless the palestin find a way to assum control ov the forc of viol in palestin in short on auth and on gun it's hard to see how israel ev if it could be persuad to withdraw from the west bank on pap would ev do so in practice
th obam admin understand cannot deal with the hama issu now
instead it seem to subscrib to the field of dream school of diplom if you build it they wil come
according to thi log an agr between israel and the palestin auth would leav an already weak hama no cho but to put up or shut up
the on problem is that for that to work the it that they build would hav to be an agr so compel that the vast maj of palestin would ral around it
that's very hard to see now
no help from obam the presid would lik to be a hist peacemaker
and he mad clear in his 2012 interview with jeffrey goldberg that he is very frust with prim min netanyahu
but to hav a fight with thi israel prim min ov the poss of a long-shot israeli-palestinian deal doesnt ad up
a produc fight with israel that end up produc a hist peac deal wher everyon win is on thing
but right now that deal is nowh in sight
indeed right now obama's pri ar ukrain ir preserv a domest leg and maintain democr control of the sen in the upcom midterm elections
he has littl int or capac to forc press netanyahu for a deal
people may think that a second-term presid free from the nee for re-election is fre to tak a big gamble
but it has real nev been the abs of polit constraint as much as it is the pres of real opportun that driv presidents
obama doesnt want to fail
no caus for alarm
the od of a conflict-ending agr between netanyahu and abba in which the cor issu that driv the israeli-palestinian conflict ar resolv ar slim to none
think outcom not solutions
but thi isnt a caus for despair
kerry's relentless and skil in eng the party hav cre a process that wil at least surv the us-imposed april deadlin for a peac deal and liv at least until year's end
nobody want to be blam for the dem of the kerry process and both netanyahu and abba lik wonder--and worry about--wh wil hap if ther is no process
israel prob doesnt hav a plan b
and abba fallback to go to the unit nat and rely on the intern commun and the boycot divest and sanct mov doesnt off much prom without washington press israel
and so abba meet at the whit hous wil go wel enough
the presid deeply car about the palestin and their cause
and whil abba wont betray palestin posit for obama's leg neith wil he humy the president
kerry may yet squeez out enough from the two sid to produc a piec of paper
in any ev it wont be the palestin who spoil the party
president abba wil almost certain tel the presid pap or not deadlin be damn let us continu the import work of israeli-palestinian peacemaking
peace may not be around the corn but mor negoty almost certain are
follow us on twit cnnopinion
join us on facebookcnnopinion
the opin express in thi com ar sol thos of aaron david mil