ukrain tend high as crime prep for vot on split
kiev ukrain cnn ukrain off said about 60 russ troop in six helicopt and assist by three arm vehic cross into ukraine's kherson reg a tiny strip of land nor of crimea
kherson gov
yurii odarchenko said that russ helicopt land in the are but that ukrain bord guard repel them
the stat bord guard serv of ukrain howev said the russ troop wer stil ther and the ukrain guard had tak defend positions
the kherson reg is key to crime becaus it get elect freshw and nat gas from there
th russ said they ar in kherson to prev a poss ter attack on oil asset in the are accord to the bord guard service
no clash hav been report the bord guard said
ukraine's foreign min term the mov a milit invas and cal on russ to withdraw it forces
vote on secess sunday tend remain high in ukrain saturday on the ev of a vot on secess in crimea
the vot look set to go ahead sunday despit high-stakes diplom effort by the unit stat and the europ union
the referend wil pres crim resid with the cho of wheth to sec from ukrain and join russ or effect becom independent
ukraine's act foreign min andri deshchyts rep saturday the interim government's posit that the referend is illegitim and wil not be recogn by kiev or the intern community
the govern is prep to discuss gre autonom and econom develop for crime he said but around a tabl and not talk to the gun which ar on the streets of the crim cities
ukraine is eng in a diplom war with russ he said but is look for a peac resolv to the cris in crimea
it wil not respond to russ provoc he said
russia which the west and ukrain insist has the maj ethn russ crim peninsul und it effect milit control has com und concert intern press to halt it act ther and talk to the interim govern in kiev
but so far it has refus to budge
moscow has rep deny direct involv in crime say that the well-armed men in uniform without ident insign ar not russ troops
diplomatic mov russ on saturday veto a us draft resolv decl the crime referend invalid at a sess of the un sec council in new york
thirteen of the 15 sec council memb back the resolv whil chin abstain from the vote
russia had been wid expect to wield it veto pow as a perm memb of the sec council
addressing the chamb russ ambassad vita churkin argu that crim cit had a right to self-determination
but us
ambassador samanth pow had a scath respons describ russ as isol alon and wrong in block a resolv which had peac at it heart
the french envoy to the unit nat gerard araud said he had watch russia's act with incredulity
to acceiv russ annex of crime would be against al un principl and would turn the body into a farc he said
it would mean the sword is us to settl disputes
british ambassad mark lyal grant said the resound mess from today's vot is that russ stand isol in thi council and in the intern community
russia alon back thi referendum
russia alon is prep to viol intern law disregard the un chart and tear up it bil treaties
th mess wil be heard wel beyond the wal of thi chamber
he ap to russ to hear the voic of the intern commun and eng with the ukrain authorities
contact group deshchyts said effort to est a contact group with russ a step urg by western pow hav so far fail becaus moscow wil not agr to ukraine's ful repres within the propos body
asked by cnn wheth the govern has any plan to withdraw ukrain milit forc from crime deshchyts said al plan ar on the tabl but that withdraw is not being discussed
ukraine's parlia pass a resolv saturday to tak away the pow of the crim parlia with immedy effect accord to the kiev parliament's website
of 296 tot lawmak pres a maj 278 vot in fav of the resolution
the vot is larg symbol and is not expect to impact decision-making in crime or the sunday referendum
crimea's pro-russian govern was instal at the end of last mon aft the parlia build was tak ov by arm men who rais the russ flag
donetsk ral thousand of pro-russian support join a noisy but peac ral support the crim referend in ukraine's eastern city of donetsk on saturday afternoon
some protest cal for a referend on independ whil oth demand sep from ukrain and a un with russia
the chant russ russ rang around lenin square
ther was no sign of pro-ukraine demonst in the squ and riot pol stood to on side
th demonst then march through the city cal for the oust of donetsk reg govern sergei tarut who was appoint by the new govern in kiev
they also chant sham on you outsid the off of ukraine's sec ag the sbu which is loy to kiev
some of the protest hand out leaflet urg peopl to return to the squ sunday for furth protests
igor demin spokesm for the donetsk reg pol depart told cnn beforehand that mor than 1000 pol would be on duty for the ral in a bid to prev violence
a man was fat stab and at least 10 oth wer ind in clash in donetsk on thursday
russia blam right-wing rad group for the viol whil ukrain auth suggest it was link to russ cit who want to esc tend in ukraine
a court in the city reject an apply by donetsk city council to ban al weekend demonst in the city maksim rovinsky press secret for the city admin told cnn
the court said ther was no evid of dang to the public
many peopl liv in ukraine's eastern reg along the ukraine-russia bord ident mor with russ than with ukraine
rival moscow ral as demonst march in donetsk on saturday protest also took to the streets in the russ capit moscow
state new ag itar-tass cit moscow pol said som 15000 turn out for a ral in support of the referend in crime whil about 3000 march in protest against attempt to reunit crime with russia
the black sea peninsul was part of russ until soviet lead nikit khrushchev gav it to ukrain in 1954
ukraine was then part of the soviet union
tensions flar into viol lat friday night in the city of khark nor of donetsk and ev clos to the russ border
two peopl wer kil ukraine's intery min said and a pol off was sery injured
the arm clash involv pro-russian act and memb of a far-right group right sect the min said in an onlin statement
petrol bomb wer thrown and shot fir at pro-russian act as they tri to ent a build wher right sect memb wer hol up
police hav arrest 38 peopl in rel to the viol and confisc a numb of firearm round of ammunit and petrol bomb it said
opinion can west mak putin blink
lavrov no common vis despit us warn of cost for russ if the vot goe ahead moscow has refus to budg on the crisis
lengthy talk between us secret of stat john kerry and his russ counterpart sergey lavrov in london on friday result in littl mor than an acknowledg of the gap between them
as lavrov said we dont hav a common vision
meanwhile thousand of russ troop continu a large-scal milit dril near the ukrain border
on the sam day arm truck tot long-range gun and oth milit equip rumbl through northern crimea
at least on of the vehic seen by cnn had russ licens plates
already eight ukrain milit unit in crime hav been tak ov 22 oth ar block and 49 of 56 bord patrol stat ar in simil straits ukraine's foreign min said
kiev's new western-leaning govern which cam to pow follow the oust of presid vikt yanukovych has insist that ukraine's territ integr includ crime must be respected
moscow has insist it has the right to protect ethn russ in ukrain who it claim ar threatened by rad nat and fascists
opinion europ must check the putin doctrin disput continu estonia's defens min urma reinsalu said friday that ukrain is on the verg of a full-scale milit conflict unless russ presid vladimir putin's hand is forced
it is clear that we ar at a crossroad un secretary-general ban ki-moon said
if posit continu to hard and rhet continu to sharp ther is gre risk of a dang downward spiral
russia so far has refus to eng in direct talk with ukraine's new lead although lavrov said som commun continu with the interim govern in kiev
moscow has also deny any direct involv in crime say what's hap in the black sea peninsul is an intern matter
russia has a maj nav bas in the crim port city of sevastopol and thousand of it troop ar stat there
map why the eu and us ar out of step on russ sanct sanct warn europ nat and the unit stat hav annount som target pun against russ in addit to off of bil in aid to ukraine's fledgl government
russia has seen steep declin in it stock market and the valu of the rubl in rec days
the stat depart has caut am about travel to russ giv the poss of viol or anti-us act direct against us cit or us interests
kerry warn friday that the consequ wil be far mor stringent should putin sign off on the back-door annex of crimea
lawmakers in moscow ar due to vot next friday on acceiv crime into the russ fed should ther be a ye vot in the referendum
at the sam tim kerry op the door for less strident meas should russ opt not to tak in crime whatev the referend say and instead go along with gre autonomy
crimea echo of hist on road to yalt cnn's iv watson report from kiev and dian magnay from crime whil laur smith-spark wrot and report in london
cnn's kel morg contribut from donetsk and tim schwarz from kiev
cnn's richard roth yon pomrenz azad safarov and greg botelho also contribut