insid polit gop deb ov policy and personalities
john king and oth top polit report talk about the struggle within the republ party as wel as what the next big polit story wil be on insid polit at 830 am
et sunday and at 730 am monday through friday on new day
washington cnn it's get person on al front as republ deb the wisdom of their lead pres and future
two lead gop 2016 contend the freshm sens
rand paul and ted cruz ar in a publ spat ov foreign policy that quick becam fram around what seem to be the peren gop quest who is the heir to ronald reagan
and whil that play out two of the right's outspok and at tim outland voic ar in a war of word ov wheth conserv should see sen gop lead mitch mcconnell as a hero or a heretic
these deb ar entertain and interest not to ment tel snapshot of the struggle within the republ party and conserv mov to find a consens mess and acceiv messengers
some of it should look famili to democr who rememb the year between mond 84 and clinton 92 a party in exil from the whit hous has no singul lead and so has mor op and voc competit ov policy and personalities
then-arkansa gov
bill clinton and his merry band of democr lead council cent argu the democr party was too lib too tied to big lab and too afraid to talk about thing lik work requir in welf programs
no perhap they didnt hav the not of today's tea party
but thos wer not exact day of democr unity
democrats for the leis class was the label jess jackson put on clinton and the dlc
it was gre polit the and lik the republ tug-of-war today an instruct look at the tend in a party that at the tim was strong at the congress level but not cred at the presid level
my how the tid has turned
republicans now control the hous and hav a good chant to tak control of the sen in thi year's midterm elections
2014 midterm elect but thos success hav eas the demograph cris that confront republ at the presid level if the gop cant improv it stand among latino african-americans and millen then the path to 270 elect vot wil get mor difficult with each pass day
the demograph chang in americ ar the gop's inconveny truth
and so their transit play out now just as it did for democr in the lat 80s and ear 90s
cruz see the tea party mess as the gop's future
paul has a mor cobbleston or patchwork approach his dad's libert band as a bas a slic of the tea party pie as a build block and then outreach not alway success to young vot and african-americans and god forbid ev to the gop establishment
purity vs plur sort of
they ar hard the on voices
another freshm sen marco rubio of florid had the first crack at being label the gop savy then rankl som of the bas with his support of a path to cit for undocu immigrants
rubio is stir anew with tough talk on foreign policy and a foc on poverty
texas gov
rick perry is proof that second chant ar an am polit tradition
he bomb in 2012
but dont count him out
as cruz and paul exchang barb in the who is the next ronald reag deb rememb reag was a govern and an optimist
perry is both of those
and rememb reagan's crit includ ear competit within the gop wrot him off as not too bright
reagan had the last laugh and then some
perry is angl to get that chant in 2016 and should not be discounted
but as the party decid who it lead should be it must also answ the quest of what it mess is
it is ther that the integr of the tea party and libert into the gop caus so many interest policy ripples
th wil undoubt play out in the 2016 gop presid nomin contest when the lead quest is paramount
but it is play out now as wel in the fight ov mcconnell
to the tea party the quest isnt so much mcconnell's vot record
instead it argu is he should be judg by the company he keep or want to keep
as in form sens
robert bennet and richard lug both def by tea party prim challengers
or trey grayson who was mcconnell's cho in the kentucky sen gop prim ultim won by paul
or char crist a democr now but the cho of mcconnell and the gop est in the primary
to crit al ar mod too wil to comprom with democrats
i'm talk about the candid mcconnell has support instead of the conserv red state's erick erickson writ in his latest column urg support for mcconnell's tea party challeng thi year
anoth voc and oft controvers voic on the right an coult is a lead mcconnell defender
she not his opposit to campaign fin law chang that hav help democr and his disciplin work to get every gop sen to vot against obamac which she say giv the party a much stronger 2014 midterm message
and she not his lead in forc the obam whit hous to acceiv the forc budget cut known as the sequester
even ronald reag didnt cut fed spending
coulter wrot in a column thi week
mcconnell did and that was with a democr presid and a democr maj in the senate
sh lam a right-wing mob and nonsens jeremiad against mcconnell on the redst blog
erickson say it isnt so
there's no right wing mob on the march he writ on redstate
there's just a cle crew
if we dont cle up our own sid the gen elect vot sur will
mcconnel rais eyebrow by tel the new york tim he was confid the est would prevail ov the tea party challeng and their conserv fund sourc vow to crush them everywhere
crush or be crush was erickson's retort
we wil see if ther is a clear win in thi round as the 2014 prim play out and then as we watch the novemb 2014 results
whatever the outcom som of thes tend wil carry ov into the 2016 nomin contest
sometimes as both reag and clinton prov thes intern tend can on be settl or at least mor neat man by win the whit hous