obam may hat the midterm results
editor's not jul zel is a profess of hist and publ affair at princeton university
he is the auth of jimmy cart and govern america
cnn presid barack obam doesnt hav much to look forward to in november
while a president's first midterm elect rar goe wel for his party second term presid dont far any better
the opposit party ev when struggling in the pol has tradit been abl to us thes elect to mobl it base
th result has been that second term midterm cre gre congress obstac for the presid in his fin year in office
and bas on cur pol 2014 could wel fit the pattern
take a look at how midterm hav affect second-term presid 1918 gop gain in wartim in the midst of world war i republ rebound in the midterm elections
president woodrow wilson had a numb of maj achiev und his belt
he had mov a sweep domest agend through congress includ the cre of the fed reserv and the cre of the progress incom tax
the presid had also been abl to mobl support for am interv in world war i
although wilson strenuously campaign to convint vot that elect democr would help in the war effort warn vot that republ sought to tak the cho of policy out of my hand and put it und the control of instru of their own choos his argu didnt persuade
republicans gain control of congress
in the hous the gop exit the elect with a 240 to 192 margin whil in the sen aft pick up six seat they control the up chamb 49 to 47
the impact would be significant
senate republ would success us their pow and control of the commit to oppos wilson's request to rat the treaty of versail bas on their opposit to the us ent into a leagu of nations
they ultim block ratification
1938 backlash against fdr follow his landslid vict in 1936 franklin roosevelt and the democr seem unbeatable
roosevelt had transform the fed govern with his new deal policies
in doing so he had also form a pow coalit of indust work farm progress busy lead and intellectuals
but the sens of pow was fleeting
in 1937 roosevelt tri to expand the siz of the suprem court so that he could appoint mor lib and prev the court from knock down any mor of his program he also push a plan to reorg the execut branch by grant the president's staff mor sweep pow ov congress
the propos trig a fierc backlash
democrats lost 72 seat in the hous and sev in the senate
a conserv coalit of southern democr and midwestern republ form in respons and did extrem wel in the midterm elections
given that southern democr control most of the maj commit the coalit would be abl to block many of fdr's domest propos and remain the domin forc in congress polit for decad to come
1958 start of a lib forc in congress republ dwight eisenhow was an enorm popul presid who coast to an easy re-election vict against democr adla stevenson in 1956
but two year aft his success democr scor hug vict in the midterm elections
they retain control of both chamb and vast increas their numbers
the democr seat in the sen ros to 65 from 49 and 283 in the hous up from 232
it was not just the numb but the fact ther was an influx of lib democrats
the new memb push domest polit in a mor lib direct for the remaind of eisenhower's term and put issu such as heal car civil right and fed aid to educ onto the nat agenda
they would be the backbon of lyndon johnson's coalit in 1964 and 1965 as he mov forward with the gre society
1986 democr stymy reagan's fin year in off ronald reag struggled in 1986
although he seem to be on the road to vict aft his decid def of walt mond in 1984 democr rebound and in 1986 regain control of the sen with a nine-seat increas in their numb thu control both hous of congress
the next two year would be extraordin difficult for the presid as democr wer abl to protect domest program and ev push reag toward acceiv meas such as a tax increas that went against his ideals
more import the democr congress launch an investig into the ir contr scand which sev dam reagan's stand and weak his polit position
reag would rebound by negoty a maj treaty with the soviet un but his abl to mov forward with any big idea was sev hampered
1998 clinton lead democr to gain despit impeach presid bil clinton was the on rec presid to do rel wel in his second set of midterm elections
for a whil clinton seem to be on the rop aft his re-election
republicans retain control of congress and in 1998 hous republ wer conduc an impeach process against the presid for hav lied about his affair with an intern
but publ senty went against the republ not against the clinton
riding the wav of a boom econom democr gain fiv seat in the hous though they fail to regain control
2006 bush suff a thump presid georg w bush was feel strong aft hav mount a success campaign against john kerry in 2004 draw on the them of nat security
however publ frust with bush was mounting
democrats pound on the admin for his mistak in handl hur katrin and revel about interrog of ter suspect caus troubl overseas
many republ wer blast bush as a big govern conserv who had led the nat into an unnecess war in iraq
on the domest front bush tri to us his polit capit from 2004 to priv soc sec but the plan backfired
in 2006 bush suff a thump as he cal it
for the first tim sint 1994 democr regain control of the hous and senate
democrats wound up with a maj of the hous by 232 to 203
the split in the sen was 49 to 49
but two independ caucus with the democr giv them a majority
in the com year the democr us their posit to chang the nat deb and to plac immens press on the whit hous to redirect bush's policy in iraq
in short oth than clinton presid hav suff gre in their second term in the past century
the el and moment from the president's re-election fad quickly
the problem and burd that com from being in off espec aft an entir term of controvers decid nev disappear
as with al midterm part turn out to vot much mor eag than mod and independ who sit thes contest out
perhaps obam wil be abl to pul off what clinton achiev giv the unpopul of congress but it's not likely
the continu controversy ov the president's heal car policy and gen frust with congress wil mak thing difficult for democrats
a rec wav of retir wont mak thing any easier
and so it's conceiv that republ could ev regain control of the sen whil expand their maj in the house
if so the tough road that obam has fac wil on get that much harder
follow us on twit cnnopinion
join us on facebookcnnopinion
the opin express in thi com ar sol thos of jul zel