day pass no word of lov ones
cnn new zealand danic and paul week ar no strangers to disaster
the couple's eldest son lincoln was born in the midst of an earthquak in christchurch in 2010
just ov three year lat in decemb 2013 they wer in a car accid aft mov to australia
so when paul left for a min job in mongol ear thi mon the coupl took precaut danic says
paul couldnt wear his wed ring on the min sit so he left it and his watch at hom with instruct to pass them on to his two son should anyth hap to him
on his way to mongol paul travel on malays airlin flight 370
as she speak to cnn's pier morg on thursday danic grip her husband's wed ring whil fight back tears
it' been fiv day sint mh370 van but with littl inform about the plane's whereabout the wait feel lik an eternity
that's the toughest part every day wak up and look on the new and see that there's noth and ther ar no cal from malays to say we'v found someth week says
he was the most amaz husband and the most amaz father
he spent so much tim with his kid she says
approximately 5000 mil away at a hotel near the beid capit intern airport hu xianqu wait anxy for new of her husband mao tugui
the coupl last spok on march 2 when mao a paint was about to board a flight to malays to attend an exhibit of his work
for hu lik many famy of thos on board flight 370 grief is quick turn to frustration
there has been no word of her husband for day and confus report about the search and rescu miss ar on mak the wait mor agonizing
no on real upd us she says
question and answ whil many chines rel of passeng on board flight 370 beg travel to kual lump on tuesday hu and her daught decid to stay in beid concern that the langu barry would on mak it mor difficult to understand what was happening
malaysia airlin off to transf chines and ind rel of miss passeng to kual lump for bet car and comfort but som hav declined
i dont see the point in going to kual lump and see the sam inform k s narendr tel cnn from india
his wif chandrik sharm was on the flight
it's bet to stay in chenna wher i'm surround by famy and friends
sharma the execut secret of the intern collect in support of fishwork had been on her way to mongol for a conf of the un's food and agricult organization
her husband say he's receiv littl direct assist or inform from auth about the search op and rely on press conf and new report but that has thu far amount to nothing
see mor of our cov on miss malays airlin flight 370 malaysia's prim min najib razak has ap to rel to be patient
the famy involv hav to understand that thi is someth unexpected
the famy must understand mor effort hav been mad with al our cap he said wednesday
more than half the passeng on board flight 370 wer chinese
martial art expert and stunt man ju kun was among them
the 35-year-old whos film credit includ the grandmast and the forbid kingdom was set to begin film a new netflix sery marco polo in the com weeks
netflix and it produc partn the weinstein company said in a stat that they wer deeply sad by the news
ju kun who was on board was an integr part of our produc team and a tremend talent
our thought and pray ar with his famy at thi difficult tim the stat said
chinese actress zhang ziy post a tribut to ju on her weibo account he is a sint kind and hardwork man
like many of thos on board flight 370 ju's soc med account has been flood with com from strangers many pray for his saf return
around the world commun hav gath to pray for the miss and off comfort to their lov ones
on monday malays sang song and lit pap lantern at a candlelight vigil in kual lumpur
crowdsourcing the search in nearby pet jay memb of the st frant xavy church hav been hold spec pray sess for patrick frant gom an in-flight superv who was on board the flight
it's stil difficult for us to com to term with what has happen
i can on say that my fath is a quiet person but also can be a jok his daught nikk gom told cnn
he is very ded to his job and took his respons very sery as al crew memb would
malaysia airlin wil retir flight cod mh370 and mh371 as a mark of respect to the passeng and crew the company said in a stat thursday
many hav turn to digit platform to off comfort word and tribut sit hav been cre for the flight's captain and crew
a facebook profil thought to be that of pour nour mohammad an 18-year-old ir who us a stol passport to board the plan has scor of mess of support from strangers
i dont know you but i pray that you ar saf somewh in thi world writ on user
may you and the oth passeng and crew on malays flight 370 be found saf and may yo journey continu to find yourself saf in yo moth sic arm again
back in chin huang lu a teach at an el school in guizhou provint wait for word of her friend huang yi
the 30-year-old work for the technolog firm freesc in the company's tianjin office
sh was on the plan with 19 oth colleagu when it disappeared
the wom hav been friend sint they wer teenagers
she' kind liv and a good person to talk with huang lu said
the pair kept in touch online
yi who has a five-year old daught nam yuanyu would oft talk to huang lu about famy and rais children
i've been wait worry sint i heard the news
i hop to see a miracle
yi pleas com back yuanyu nee you she said
read off disput report that malays airlin flight 370 kept fly for hour interact what hap to malays airlin flight 370
read transponder's fat may prov key to solv malays airlin puzzl read malays airlin flight 370 day pass no word of lov on dayu zhang and seren dong report from beid soph brown wrot from hong kong
cnn's anjal tsu and eu mckirdy contribut to thi report