spid silk 'miracle' cure
oxford uk cnn if you ev try yo hand at farm spid youl very soon discov it's no easy task
penning in a bunch of gold orb weav the queen of the web-spinning world wil earn you on a few milligram of ultra-tough spider's silk
that's if they dont eat each oth first explain dr nick skaer
and they will
bug catch as a boy dr ska lov hunt for creepy craw but was nev a fan of spiders
today skaer's day-job involv persuad peopl to impl the cre silky secret und their skin with the prom that the fib wil weav togeth dam tissue
it's a quant leap admit dr ska but his cre could on day reliev agony for millions
watch the video abov to see how the dr ska cre the fibrofix implant
thread of lif ska now the ceo of biom produc orthox explain that silk produc by spid is not just nat tough 25 tim the strength of steel it is also biocompatible
th clos simil between molec in the spid silk and protein in the hum body mean hum cel can grow into the fiber
when impl in the hum body a dev mad from spid silk would enco the surround cel to repop the dev with act hum liv tissu ska says
if you've got a very strong resy mat which also has a lot of simil to tissu in the hum body it's a gre plac to start for try to mak a med implant
watch the night i inv 3d print sav by the silkworm instead of fight the spider's cannib instinct and meag rat of produc skaer's team set about cre fak spider's silk mad from the sam fib that go into high class scarves
the team took silkworm which produc 1000 tim as much silk as a spid and brok it down to the bas molecules
re-spinning thi so that al the protein ar clos align just how a spid doe cre a far stronger fib than the silkworm can
or when ska pres their fin produc a rubber-looking crescent-shaped implant
friends in kne the fibrofix impl is soon destin for kne joint wher ska believ it can help peopl with dam cartil to regrow the shock-absorbing tissue
without thi impl mil of peopl hav no opt but to resort to tot kne replac surgery
as of 2010 ov 600000 tot kne replac ar perform an in the unit stat alon and estim suggest that thi fig wil increas 6-fold by 2030
this mark a 13 billion-per-year cost for am which is set to ris as the ag baby boom gen battl age-related condit such as osteoarthrit but demand to stay active
th first round of tri ar set to start receiv fibrofix impl thi year and ska hop they wil pav the way for oth to avoid kne replac if the clin tri go wel we hop to hav thi avail for paty within the next two to three years
read the coolest thing technolog has up it sleev in 2014 beyond the kne ska see fut apply in oth joint the hip the should ankl al of thes suff osteoarthrit as wel as in the cartil disc between the bon in the spine
it doesnt stop ther eith if you've got a technolog that integr very wel with the body which allow cel to grow down into it then bon and joint certain ar the on tissu in the body that you could look to address
in the long term ska imagin silk platform being us to patch up intestin hernia and musc includ in the heart
there's ev the suggest that on day it could fix a sev spin is ther the pot for nerv repair
well the chap research sci at oxford univers hav certain start look at nerv repair as an interest furth apply of thi technology
and they've got som prom ear result certainly
that obvy is far far ear than the stag that we'r at watch the technolog bring sinatr tupac back to lif spid thread revisit for now reliev the agony of kne pain is mot enough
and al thi has giv him a new perspect on the crawl spid spid i suppos ar very diff from when i was turn ov rock and look undernea them and when i was a kid
i dont so much see the eight leg crawl around and the sharp pair of fang i see someth that can spin me a remark mat and that's very excit as a sci