wahlberg get 'thin as possible' for movie
cnn talk about a transformer
mark wahlberg who show off rippl musc in 2014's transform ag of extinct is los as much weight as he can for a remak of the gambler
photos from the set show that the 42-year-old has becom not skinny in ord to portray a lit profess with a gambl problem
the actor's lean phys was first not in janu and he confirm to extr at the tim that he was los the weight for a role
i'm try to get as thin as a poss can wahlberg said
i was at 195 when i was doing transform and right now i'm at 158
so mayb il go to 150 149 145
obviously in ord to drop that much weight whil film wahlberg's had to commit to a diff diet on that he admit struggled with
anytime i smel food i get crazy he told extra's mar menounos
my daught was eat thi blueberry scon and i want to lik i was going to jack her for it
i was lit going to rob my almost 4-year-old daught for her littl blueberry muffin
judging from the on-set photo it look lik wahlberg was abl to stick to his guns
the gambl which also star john goodm jessic lang and michael k william is due to ar in 2015