hollywood reimagin in ghana
editor's not cnn's on the road sery bring you a gre insight into the hist custom and cult of ghana
cnn expl the plac the peopl and the pass un to thi afr nation
cn how would you design a movy post for a hollywood blockbust you'd nev seen fil with charact you knew noth about and act you'd nev heard of
would jean-claude van dam look lik a surg glov stuff ful of walnuts
would cujo the kil dog look lik a guil spaniel that'd devo the cak at a child's birthday party
would jam bond hav the stun express of a man who had just receiv a larg elect bill
if yo on brief was to pack a crowd into a mobl afr cinem hal you might also want to ad som incid aly shoot las beam from their eyes
in ghan wher the gold ag of movy post dur the 1980s and 1990s produc thes lurid vibr and outland origin the movy post may be a dying art form but it has sint becom big business
western collect now pay thousand for prim exampl of the genr and the art who ont churn out the post to fil ghana's dilapid cinem club ar find a new leas of lif reproduc them for art aficionados
jeaur ok afutu 39 beg paint the post when he was 14 year old but now work from his hom in accr ghan to produc them for art deal sel them for between 75 and 100 apiece
currently put the fin touch on a canva cut from a flo sack he's produc a distinct ghana tak on the biop mandel long walk to freedom
action and war work a lot  and wom too both act afutu told cnn show that hollywood's time-honored recip of sex and viol is an intern language
it al depend on what the audy prefers
read mor keep africa's star of democr shin when he produc thes origin for ghana's cinem club --- oft no mor than row of seat in the op air around a gas-powered gen and a tv set with a vcr --- his job was to draw crowds
to do thi he apply his imagin to the canva produc scen that didnt ex in the origin film plac drip kniv in the hand of zomby assassin or gun at the ready for vary hero who had no weapon in the act film
these sur vary spic up a whol gen of schlock-horror film that cam out of hong kong hollywood bollywood and it nig equ nollywood
as on crit remark the post ar oft far bet than the films
african art deal erny wolf who first not the movy post in 1990 whil research ghana's phenomenon of fantasy coffin said that despit the untut styl of the post the art knew exact what effect they want to create
they ar definit very very good art and they paint exact what they want said wolf who has writ two book on the genr extrem canva and extrem canva 2
having look at hundr of them you becom aw of their individ hand their idiosyncrasy and their brush strokes
the on that interest me the most ar the on bef the tradit died in about 2000
read mor bamboo bik turn around fortun ghana's econom develop combin with afford technolog that has brought hom entertain within the reach of many ghana put paid to the movy post cot industry
while they're stil being mad by som of the art that produc them two decad ago wolf explain they're now mad as commod for the art market
the best of the gold ag movy post from the 80s to the lat 90s ar the on wher they just complet went out into the land wher ther ar no rul he said
it gav them an incred freedom to be expressive
they mad im that they knew would bring peopl in and no on was look ov their should to tel them they couldnt do anything
the on restrict he said was the siz of the canvas which fel strictly into two vert on sid of a 50kg flo bag or two sid stitch together
apart from that ther wer no limits
he said the work also fal into the realm of art artifact wher the evid of their origin purpos is also part of the narrative
th work pattern of their us hav been nail up by their corn and splattered by mud from pass bus also tel a rich story about how they wer util wolf said
with rar vint work fetch as much as 15000 and gold ag post routin going for between 1500 and 3000 a market in fak has emerged
wolfe howev remain sanguine
it's poss to say they're fak but it's also poss to say they're a hom he said
while the commodit vert ar stil artwork in their own right wolf said they occupy a diff zon to the stark immedy of the originals
there' a big diff between thos work that wer produc for them ghana and the on that ar produc for us collectors
cnn' on the road sery oft carry spons origin from the country we profile
however cnn retain ful edit control ov al of it reports
read the policy