new mus serv from neil young
cnn neil young has long complain about the qual of digit mus formats
now he's doing someth about it and he's get help from som friends
bruce springsteen eddy ved tom petty and sting wer among the art who join young in a video to promot a kickstart campaign for pono a digit mus serv and dev design to bring the highest-quality digit mus to consum accord to it press announcement
young himself was at austin's sxsw ev to demonst the service
every part of my body is get hit with thi young said of his expery with pono accord to the san jos mercury news
my soul is feel it
i am doing what i us to do i'm listening
i'm feeling
and i'm experiencing
i am liv music
the ide behind pono is to boost digit mus from the compress and lossy form to high-quality resolution
pono wil stream mus in 24-bit 192 khz sound bright and mor pres than the underw list as young describ it provid by mp3s and ev cds
the dea of the hom stereo system young has mad no bon about his disgust with mp3 and simil fil formats
the simplest way to describ what we'v accompl is that we'v lib the mus of the art from the digit fil and rest it to it origin art qual as it was in the studio young wrot last year on pono's facebook page
his mus friend wer al for it
i got my drug of cho said ved who was part of an all-star lineup rav about pono in the video
it's now pot again
he's develop someth that cre a very warm analog sound that tak ev yo digit record that giv them  a clos an intim that digit record can los very easy said springsteen on the video
the kickstart campaign was intend to rais 800000
it blew past that goal in less than 24 hours
a of midday et wednesday it's clos in on 15 mil in pledges
though the sit tak don in any amount peopl who pledg 400 or mor wil receiv a ponoplay art sign sery from their cho of mus includ patt smi beck and the dav matthew band among many
the ponoplay dev hav 128 gb of mem cap of stor 1000 to 2000 high-resolution digit album accord to the press release
they wil be sold at ponomusiccom for 399 each
albums wil lik sel for between 1499 and 2499
the campaign run through april 15