when shop cart go rogue
cnn the year was 1937
it was the dawn of the soft-drink machin the first tub of the lincoln tunnel  and the shop cart
inventor sylv goldman's prototyp for the shop cart was noth mor than two wir basket attach to a fold chair but it was the start of what would becom a supermarket staple
when it first cam on the scen custom wer reluct to us the cart
but by the 1960s they wer so ubiquit that a new problem had ar the rog shop cart
chicago supermarket own anthony dinolfo was so enr by the volum of stol shop cart pop up in plac decid not supermarket in auto repair shop people's bas and at the bottom of riv that he went on a crusad to return them to their right owners
in 1969 he deem febru return shop cart to the supermarket month
dinolfo died in 2009 but his crusad reappear each febru on vary websit and internet forum and was ev acknowledg by the us cens bureau
when we brought thi to the at of the cnn ireport commun our contribut ment that until now they had nev not how prev wayward shop cart were
whil it may be easy to writ off dinolfo's crusad as just the hyst rant of a disgruntl busy own retail report cart theft to be a cost problem
shopping cart cost anywh from 75 to 150 each accord to bret osterfeld of gatekeep systems
retailer find custom amb toward the issu frust but most peopl cant help but think that ther ar gre caus to rais aw about
am i suppos to real feel sorry for the grocers
asked jeremy nix from denver
the gre cart robbery ron fong presid and ceo of the californ groc assocy found that stor that report the greatest loss ar loc in neighb and city wher few peopl own a car but stil nee an efficy way to carry their grocery home
onc the shop ar fin the cart rar return to the store
fong said that he's seen many innov us for shop cart such as port barbecu gril loung chair and ev shelters
he not that many homeless peopl us them to transport their belongings
in novemb hawai stat lawmak tom brow attempt to cle up the state's homeless problem by tak a sledgeham to abandon shop carts
hawaii has the country's highest rat of homeless per capit brew said his solv was meant to enco them to seek out shelters
i get a lot of complaint about stol and abandon shop cart in waikik and i was think as a publ serv what can i do that would be pract and i can lit do overnight
brower told cnn affy kitv
i'm not doing anyth diff than doing a commun cleanup or what the city's admin has tri to do with the issu of peopl illeg camp on the streets
supermarkets and commun memb ar the on on upset about the stray carts
the city of sant an californ report an an cost of 50000 to retriev abandon shop cart from loc streams and rivers
across the country john long presid of the maryland nonprofit cle bread and chees creek said that volunt hav remov mor than 200 shop cart from the creek that drain into the chesapeak bay sint 2009
they cre an environ hazard by trap wildl and caus art dam along the stream which lead to flood and erod long said
stores ar work to contain the problem through the us of cart contain system the wheel lock when they reach the bound of the store's park lot and by hir company to loc and return the cart for a fee
and yet it's not hard to find plenty of shop cart in the wild  scroll through the gallery to see som of the spot wher cart hav turn up