here's how the sat wil change
cnn the sat colleg exam wil undergo sweep chang on what's test how it's scor and how stud can prep colleg board presid and ceo david colem said wednesday
standardized test hav becom far too disconnect from the work of our high schools colem said at an ev in austin texas
they're too stressful for stud too fil with mystery and trick to rais scor and ar necess cre mor college-ready stud he said
the sat to be releas in spring 2016 is design to chang that he said
the test wil includ three sect evidence-based read and writ math and an opt essay each retool to stop stud from simply fil a bubbl on the test sheet
no long wil it be good enough to foc on trick and try to elimin answ cho colem said
we ar not interest in stud just pick an answ but just their answers
the test wil shift from it cur scor scal of 2400 back to 1600 with a sep scor for the essay
no long wil test tak be pen for choos incorrect answers
to prep stud for the test the colleg board wil partn for the first tim with khan academy to provid fre test prep mat start in spring 2015
afterward income-eligibl stud wil receiv fee waiv to apply to four colleg for free
why the test is chang the last maj chang to the sat cam in 2005 when it alt som quest form ad a writ essay and chang it scor scal from 1600 to 2400
for thi chang colem cit the nee to cre mor opportun for stud rath than obstruct them with test quest that felt detach from their educ and the prep colleg needed
coleman who join the colleg board in 2012 has spok crit of his organization's test and discuss how it could be improved
admissions off and counsel hav said they find the dat from admit exam us but ar concern that thes exam hav becom disconnect from the work of high school classroom and surround by cost test prep colem said
in rec year anoth exam the act has gain popul as sev stat adopt it as part of their standard test programs
and whil the maj of four-year colleg requir an exam scor for admit hundr of schools hav shift to test-optional policy that allow stud to decid what to submit or wheth to shar a test scor at all
indeed stud grad and the academ rig of their cours weigh mor heavy in colleg admit decid than standard test scor class rank or profess interest in a particul school accord to the nat assocy for colleg admit counseling's 2013 stat of colleg admit report releas in january
the report was bas on survey sent to publ and priv high schools postsecond institut and dat from the colleg board the us depart of educ and the us cens bureau
i'd lik to be optim and believ som of thi is going to be good said stev syverson a memb of the nacac board and dean of admit emerit for lawr univers in appleton wisconsin a test-optional school
i just dont know how it wil work out
syverson was part of nacac's commit on standard test that in 2008 urg standard test mak to adh mor clos to school curricul colleg to consid mor about appl than seduc simpl test scor and socy to stop rat schools bas on standard test scores
syverson was intrigu by the khan academy partn he said and pleas with the direct colem seem to be tak the test
he wond wheth fee waiv and oth chang ar meant to draw back stud and schools that hav turn away from the sat or test in general
until he see the pass stud wil be read the quest they're answ and the way colleg react he has to remain skeptical
some of thi is just words
they had a lot of gre langu around the last chang in 2005 syverson said
the angst about the exam has just continu to grow
how the test wil chang sect of the redesign sat might sound simil to the cur test but the chang ar sign colem said
the read and writ sect wil includ quest that requir stud to cit evid for their answ cho and wil includ read pass from a broad rang of disciplin includ sci hist soc study and literature
test tak wil no long be ask to complet sent with obsc word they might hav mem from flash cards
instead stud wil hav to consid the context of how word lik synthes and empir ar used
they're not sat word as they've com to be known colem said but word stud ar lik to encount again
we must do al we can to fost thi dai work that prep stud colem said
the math sect wil no long allow calc to be us on every portion
it wil foc on dat analys and real world problem-solving algebr and som mor adv math conceiv area that most prep stud for colleg and car colem said
it is not that help to tel stud to get ready they should study al of math colem said
the essay which the sat ad in 2005 wil now be optional
sat essay hav fac crit ov the year from educ who said they focus too much on what test tak wrot not wheth their stat wer tru or their argu reasonable
coleman said the colleg board would now tak respons for unintend consequ of how the essay test was designed
essays wil be scor sep from the rest of the test and the prompt wil remain bas the sam in every test it wil ask stud to consid a pass and writ an essay that analys how the auth mad an argu us evid and styl ideas
the redesign test wil tak about three hour with an addit 50 minut for the essay and wil be admin by print and comput the cur test is avail on pap only
how stud can prep last year when colem annount plan to redesign the sat he said it would launch in 2015
toward the end of 2013 he delay the launch to 2016 in ord to allow partn mor tim to prepare
that mean mor tim for stud educ and guid and admit counsel to understand the chang and mor tim for the colleg board's khan academy test prep program to gear up
partnering with the fre onlin resourc is intend to mak the sat mor transp and cut back on perceiv of ineq around expend test prep serv colem explain wednesday
if ther ar no mor secret colem said it's very hard to pay for them
students classroom ar meant to be the best prep for the redesign sat
the colleg board's khan academy tool wil suppl that learning
it's going to meet stud wher they ar said salm khan the khan academy creator
well tak you as far back as you nee to go or as far forward as you nee to go
khan emphas that he is plan to challeng the ex test prep industry by off high qual easy access tools
th isnt just a hey sint it's fre it's bet than noth he said
our int in thi partn is thi wil be the best thing out ther and it hap to be free
on april 16 the colleg board wil releas mor detail spec about the test and sampl test questions
some khan academy tool wil be avail to help stud tak the sat bef the redesign exam launch colem said
for stud colem said we hop you breath a sigh of reliev that thi exam wil be focus us op clear and align with the work you wil do throughout high school
what do you think of chang to the sat
share in the com on twit cnnschools or on cnn living's facebook pag