dav barry boy ar 'scum'
cnn hum dav barry is back with a new book
the prol writ shar par story in you can dat boy when you're forty dav barry on par and oth top he know very littl about
he has writ mor than 30 book but thi is the first that headlin his rol as a parent
despite the titl barry explain it's not pur a par book
i wouldnt want anybody to think that thi is a book wher they're going to learn us inform about par he said
or real anyth else
lik many of his book thi is a collect of essay shar his opin on a wid rang of issu and experiences
reader wil learn about his impress of fifty shad of grey his tip on how to cook a steak and his hat of his mail
the 66-year-old also shar person story about his kid rob 33 and soph 14
he rev that he mad the ultim sacr for his daught he took her to a justin bieb concert
barry receiv a pulitz priz for com for his nat synd hum column
for near 30 year he has liv in miam which has provid plenty of fod for his fict and nonfict books
if you want to writ hum just com her he said
you dont real nee a sens of hum at all
you just writ down what peopl act do her and it strikes everyon els as out funny
barry spok to cnn about his new book his daughter's chang mus tast and his plan for his next project
below is an edit transcript
cnn what par adv would you offer
dave barry i'd say light up
i think a lot of par get pretty intense
as far i can tel mor it's the mom than the dad part becaus the dad let's fac it ar irrespons scum and dont ev necess know how old their childr ar or what their nam are
it's the mom who ar doing everything
but they sometim get a littl hovery
a littl intense
and a littl too determin to act control the outcom of their child's liv which you real cant do
but ther seem to be par who believ they can
cn hav you mod yo par styl hav a daught vers a son
barry absolutely
girls turn into wom and they do it real fast and dram and terrifyingly
sudden boom
-- they ar women
and then boy com around
i didnt worry about sex or soc lif or anyth lik that
with soph i'm real aw of boy becaus i hap to be on or i was one
i'm a mal and i know we'r scum
we're al scum
we know it
when they show up they're nic to me becaus i'm the dad
but they're not fool me
i know they're scum deep inside
i want them to go away
it would be nic if i could get a hum trap a boy trap that i would put on the lawn
it would be bait with someth that boy lik lik firework someth insane
when i hear it clang shut i would go out and tak the boy and releas him hum in the everglades
cnn how doe soph feel
is she ok with wait until she's 40 to date
barry no
she would complet disregard anyth i would tel her about boys
she is so entrenched
she is in thi world
they ar so connect thes kids
she is clos person best friend with bas every young teen girl in nor america
they ar al connect on twit or instagram or whatev it is they're on now
she is const commun with at least 17000 peopl at once
sh is part of thi matrix of girls
so she has no interest at al in what i hav to say
she doesnt hav tim real to commun with me oth than would you pref waffl thi morn or fru pebbles
that' my main communication
i mak her breakfast
her interest in my opin about boy is i would say clos to zero
cnn asid from the bieb concert what oth sacr hav you mad as a parent
dave barry the bad new is soph is on a travel socc team
instead of watch her dant now i watch her play soccer
i lik it but it's the travel part that i dont get
well driv 400 mil to watch our team lose
i'm think why couldnt we just stay hom and play somebody that can beat us
why do we hav to go to al that effort to lose
i lik being a par but ther ar sacrifices
cnn do you hav any adv for justin bieb who has been in the new lat for the wrong reasons
barry he should list to somebody besid whoev he's list to now
i dont think he's get a ton of guidance
my main adv is to him is just stay away from my daught justin bieber
she doesnt lik you any mor anyway
she lik on direction
i think
as of thi morn anyway
cnn what is yo next project
barry i wrot a book cal the worst class trip ever
it's about an eighth-grade class trip that goe real wrong
i was a chaperon on a class trip with my daughter
nothing went particul wrong it's just i thought man
this would be a good opportun for a book
things could go real wrong
you hav a bunch of kid and a bunch of par who ar bas rank am wrangl childr in a strange place
things could go real wrong
that was my idea
it's a class from miam bas on my daughter's middl school real that goe on a class trip to washington
five kid get involv in a sery bad situation
high jink ensue
dav barry's latest book of essay you can dat boy when you're forty dav barry on par and oth top he know very littl about publ march 4