'mean girls' charact wher ar they now
ewcom  thi is wors than wear sweatp mean girl isnt get a tin fey-penned sequel
despite som hop spec from fan rec fey confirm the new to extr on wednesday say we'r com up next mon on the 10-year annivers of the origin movy we'r going to see if there's any way to get everyon togeth but not a movy sadly
we're al past high school age
mean girl 2 the 2011 tv movy sequel with a whol new group of girl is best not mentioned
 lik any good twenty-something i lov the movy but the no sequel new is tot for the best
there's no way peopl wouldnt be disappoint by whatev they cam up with and now fan can just continu to watch and lov the origin as the perfect high school satir that it is
for thos that would lik a littl mor al hop isnt lost fey is direct her energy toward a poss mean girl mus which she told ew about last year in her ew interview
since fey has mad it clear we ar going to get regin and gretchen's high school reun just for fun we went ahead and pict wher the whol fetch gang is now 10 year post-high school
regina georg regin georg continu play lacross at the colleg level and subsequ join a sor which she was ultim kick out of aft an email she wrot clev ber her sist went viral
she now work in pr and her assist has told her she isnt allow to tweet anym as her cut pitch-perfect insult hav offend everyon from the modern famy kid to the highest level of the unit stat government
anna winto has been noth but impressed
gretchen wien gretch got pregn by her los boyfriend seny year of colleg and then ditch the guy joey donner
aft giv bir to bell that nam is tot going to hap she decid moth was her tru calling
recently she's the kindergart help in bella's class mak sur every person get a valentin includ the cut singl dads
she also work part-time as an admin assist at pillsbury wher she is regul comply on her hair
cady heron aft she brok up with aaron samuel becaus he was far too dumb for her post-high school cady list to her mom and ms norbury and attend northwestern univers gradu with a degr in mathematics
currently she's a teach and has a quiet lif with good friend includ jan but not dam he know what he did
her secret pleas is read celebr gossip but she cant help but feel for the young wom the tabloid exploit regardless of the mistak they may hav made
karen smi karen's weath report quick went vir and she was snap up right out of high school to becom on of the weath peopl for fox new a job she hold to thi day
smith stil keep up with wien and her daught via facebook she's fond of like-ing near every post and stil hasnt tot fig out hashtags
regina has not respond to her friend request
aaron samuel aaron work as a model
obsessed with his body and weight he's oft overheard decl he doesnt do carbs
damian tot heard he may hav a littl bit of a drug habit and his new girlfriend is a tot gold digger
he cri for what could hav been with cady every year on oct 3
janis ian aft gradu jan went to art school bef drop out becaus ther wer too many rules
she mov to la and whil she hat most of the peopl she meet she's built a solid car for herself as a modern painter
she nev unfriend any of the girl she knew when she was 17 becaus she enjoy the feel of supery she get whil regul check out their soc med presences
she can be found with a protest sign in her hand
damian dam becam a shameless soc climber
aft gradu from colleg in the midwest he mov to nyc wher he regul stalk celeb and appear as a hanger-on on vary real shows
he ont help rachel zoe pick out a pair of shoes
he drop whatev his last nam was and now host an eponym show on e
ms norbury achiev tot world domination
see the origin story at ewcom
click her to try 2 risk fre issu of entertain week  2011 entertain week and tim int al right reserv