oldest piec of ear found
cnn from a sheep ranch in western austral com the oldest slic of ear we know
scientists say they hav dat an ant cryst cal a zircon to about 44 bil year mak it the earliest confirm piec of the planet's crust
the find the first to describ the zircon wer publ in the journ nat geoscy on sunday
this is the oldest and the best dat of al the cryst that hav been report said john valley lead study auth and profess in the depart of geoscy at the univers of wisconsin-madison
this cryst is a transluc red valley said but glow blu when bombard with electrons
at 400 micromet long it biggest dimend is just a tad larg than a hous dust mit or about four hum hairs
the cryst was found in an arid reg nor of per austral in a low rang of hil cal the jack hil in 2001
scientists say the crystal's chem spec the ratio of oxyg isotop within it suggest that the temp on ear 44 bil year ago would hav support liquid wat and theref perhap life
two isotop of an el ar consid diff if they contain diff numb of neutrons
what we'v learn is that the ear cool much mor quick that peopl had thought valley said
the surfac form a crust much mor quick than peopl thought
a brief hist of ear our planet is thought to be about 45 bil year old but the oldest fossil ar about 35 bil year old
that doesnt necess mean that no lif ex bef that tim but no direct evid has been found yet
the first rock that hav been found deposit by wat ar about 38 bil year old valley said
but very littl is known about the first 600 mil year or so of the planet's hist known as the had eon becaus it was thought to be hell-like valley said
the lead the is that ear was bombard by met in it ear history
it took a big hit from an object the siz of mar about 45 bil year ago lead to the form of the moon
these impact vap the earth's crust and form a super-hot magm ocean
evidence includ thi zircon suggest that within the first 100 mil to 200 mil year of it ex our planet cool enough to mak crust
steam from the atmosph condens to mak oceans
once you know that ther wer oc it's very reason that ther would hav been lif that ear ev when it was on 200 mil year old valley said
how they did the study valley and colleagu report on a diff cryst from ear ear in 2001 from the sam jack hil area
but ther had been an op quest regard that cryst and oth about how to determin the age
th standard method of dat such rock involv look at the radioact decay of uran atom to lead
but if the lead has mov within the cryst ov tim thi could lead to a faul estim of age
if lead has migr away from the are of the rock being test that could mak the rock appear young than it is or old if lead has cont itself
in thi new study research us a techn cal atom-probe tomograph which allow sci to im singl atom of lead and determin the isotop ratio
scientists found that clump of lead atom had form 1 bil year aft the zircon crystallized
these clust ar tiny about 5 to 10 nanomet in diameter
all that mean that the lead atom hadnt mov enough to thwart scientist's ex method of determin the crystal's ag valley said
they determin that ag to be 44 bil year old
although incred lab their analys techn can be apply to not on addit terrest zircon but also to zircon from meteorit and lun sampl to perhap teas out a detail therm hist of magm and impact samuel bowr profess of geolog at massachuset institut of technolog wrot in an accompany artic in nat geoscience
meanwhil on mar ear and mar form around the sam tim in the sol system
just as sci ar analys the chem composit of rock on ear to learn about our planet's hist nasa's curios rov is doing the sam on mars
but on can on do so much via robot
nasa is plan a 2020 rov miss that may be abl to collect sampl for lat delivery to earth
there we may find ev mor extraordin gem red or otherw