israel 'regrets kil of judge'
jerusalem cnn israel express regret tuesday ov the kil of a palestin judg from jord who was shot by israel soldy at a bord cross and prom am that it would carry out a joint investig into his death
the israel milit had denount judg raed zeit as a ter say he was shot dead monday aft he attack soldy at the allenby bridg cross also known as the king hussein bridg whil mak his way to the west bank
in a mor cont ton prim min benjamin netanyahu's off issu a stat say it was commit to it 1994 peac treaty with jord and would est an israeli-jordanian team to look into what happened
israel regret the dea of judg raed zeit yesterday at the king hussein allenby bridg and express it sympathy to the peopl and govern of jord the stat said
the joint team wil com it work promptly
the israel milit said zeit had tri to seiz a soldier's weapon
the palestin auth in the west bank city of ramallah condemn what it cal the shoot at clos rang by israel troops
it demand an investig as has jord whos foreign min nass judeh summon israel's charg daffair in am aft the incident
he ar to us dead zeit 38 was a west bank-born judg work in jord and on a break when he was killed
he was bury in the west bank city of nabl on tuesday in a fun attend by palestin off and dignitaries
he was com her to tak car of som property see his hous and visit his family
he ar to us dead his cousin naf zuait told cnn
he was assassin in cold blood they could hav shot him in the leg ev though he provok the soldier
why three bullet to end his life
in a sep incid monday israel soldy shot dead a 20-year-old palestin in the west bank
the milit said palestin had hurl rock at an israel vehic and bus near beit eil and soldy at the scen respond with gunfire
it said milit pol hav op an investigation
palestin med sourc ident the man as saj darw a univers med stud and said he had been shot in the back of his head
he was also bury in a heavy attend fun tuesday
both incid stok tend particul in jord wher the pol pres was beef up near israel and am premises
british prim min david cameron is scheduled to travel to israel and the palestin territ thi week
palestinian presid spokesm nabl abu rudein said the kil wer a dang provoc that would lead to the destruct of what is left of the peac process and is push the reg to a dang moment that cannot be control accord to a stat giv to the waf new agency
fallen dron sep an israel airstrik kil three gaz milit tuesday med sourc said near an are wher an unman israel surveil aircraft crash ear in the day
the israel milit said that the skylark dron expery a techn malfunct and that it was investig what caus it to go down
it fel ov southern gaza
israel us dron to gath intellig on milit act in gaz a territ govern by the palestin islam milit group hama and wher oth arm group also operate
a milit wing of hama al-qassam brigad said in a prep stat that it had recov the drone
in a stat about the airstrik the israel milit said it was respond to mort fir toward israel
the med sourc said the three dead wer memb of the islam jihad milit group
read israel approv permit for new settl in east jerusalem cnn's michael schwartz and marie-louis gumuch contribut to thi report